Pandas loc[] and iloc :

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv")
df

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4      NaN  20.0
4    5   4300.0   NaN
5    6      NaN  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30      NaN  33.0
30  31  47000.0  54.0

In [3]:
df.loc[0]

ID            1.0
Income    10000.0
Age          22.0
Name: 0, dtype: float64

In [4]:
df.loc[30]

ID           31.0
Income    47000.0
Age          54.0
Name: 30, dtype: float64

In [6]:
df.loc[[0,1]]

   ID   Income   Age
0   1  10000.0  22.0
1   2  13000.0  30.0

In [7]:
df.loc[[2,4]]

   ID  Income   Age
2   3  5000.0  19.0
4   5  4300.0   NaN

In [8]:
df.loc[4, 'Age']

np.float64(nan)

In [9]:
df.loc[0:3,'Income']

0    10000.0
1    13000.0
2     5000.0
3        NaN
Name: Income, dtype: float64

In [10]:
df.loc[0:2,'Age']

0    22.0
1    30.0
2    19.0
Name: Age, dtype: float64

In [19]:
df.loc[df['Income']<70000]

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
4    5   4300.0   NaN
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
21  22  12000.0  43.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
28  29  35000.0  51.0
30  31  47000.0  54.0

In [20]:
df.loc[df['Income']<70000,['Age']]

     Age
0   22.0
1   30.0
2   19.0
4    NaN
6   51.0
7   28.0
8   45.0
9   44.0
11  23.0
12  12.0
13  56.0
14   NaN
16  45.0
17  52.0
18  32.0
19  45.0
21  43.0
23   NaN
24  37.0
25  49.0
28  51.0
30  54.0

In [21]:
df.iloc[0]

ID            1.0
Income    10000.0
Age          22.0
Name: 0, dtype: float64

In [22]:
df.iloc[[0]]

   ID   Income   Age
0   1  10000.0  22.0

In [23]:
df.iloc[:,0]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
Name: ID, dtype: int64

In [24]:
df.iloc[[0,1]]

   ID   Income   Age
0   1  10000.0  22.0
1   2  13000.0  30.0