# Pandas Concat():

In [1]:
import pandas as pd

In [2]:
sr1 = pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [3]:
sr2 = pd.Series([3,4,5,6,7])
sr2

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [4]:
pd.concat([sr1,sr2])

0    0
1    1
2    2
0    3
1    4
2    5
3    6
4    7
dtype: int64

In [5]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
              'Name':['A','B','C','D'],
              'Class':[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [6]:
df2 = pd.DataFrame({'ID':[5,6,7,8],
              'Name':['E','F','G','H'],
              'Class':[9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [7]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [8]:
pd.concat([df2,df1])

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [9]:
pd.concat([df2,df1], axis=1)

   ID Name  Class  ID Name  Class
0   5    E      9   1    A      5
1   6    F     10   2    B      6
2   7    G     11   3    C      7
3   8    H     12   4    D      8

In [10]:
pd.concat([df1,df2], axis=0, ignore_index=True)

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
4   5    E      9
5   6    F     10
6   7    G     11
7   8    H     12

In [11]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
              'Name':['A','B','C','D'],
              'Class':[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [12]:
df2 = pd.DataFrame({'ID':[3,4],
              'Name':['C','D'],
              'Class':[7,8]})
df2

   ID Name  Class
0   3    C      7
1   4    D      8

In [13]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   3    C      7
1   4    D      8

In [14]:
pd.concat([df1,df2], axis =1)

   ID Name  Class   ID Name  Class
0   1    A      5  3.0    C    7.0
1   2    B      6  4.0    D    8.0
2   3    C      7  NaN  NaN    NaN
3   4    D      8  NaN  NaN    NaN

In [15]:
pd.concat([df1,df2], axis =1, join ='inner')

   ID Name  Class  ID Name  Class
0   1    A      5   3    C      7
1   2    B      6   4    D      8

In [18]:
pd.concat([df1, df2], axis=1).reindex(df1.index)

   ID Name  Class   ID Name  Class
0   1    A      5  3.0    C    7.0
1   2    B      6  4.0    D    8.0
2   3    C      7  NaN  NaN    NaN
3   4    D      8  NaN  NaN    NaN

In [19]:
pd.concat([df1, df2], axis=1).reindex(df2.index)

   ID Name  Class   ID Name  Class
0   1    A      5  3.0    C    7.0
1   2    B      6  4.0    D    8.0

In [20]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
              'Name':['A','B','C','D'],
              'Class':[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [21]:
df2 = pd.DataFrame({'ID':[5,6,7,8],
              'Name':['E','F','G','H'],
              'Class':[9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [23]:
pd.concat([df1,df2], keys =['df1','df2'])

       ID Name  Class
df1 0   1    A      5
    1   2    B      6
    2   3    C      7
    3   4    D      8
df2 0   5    E      9
    1   6    F     10
    2   7    G     11
    3   8    H     12

In [25]:
pd.concat([df1,df2], keys =[' first df',' second df'])

             ID Name  Class
first df  0   1    A      5
          1   2    B      6
          2   3    C      7
          3   4    D      8
second df 0   5    E      9
          1   6    F     10
          2   7    G     11
          3   8    H     12

In [26]:
pd.concat([df1,df2], axis=1,keys =[' first df',' second df'])

  first df            second df
        ID Name Class        ID Name Class
0        1    A     5         5    E     9
1        2    B     6         6    F    10
2        3    C     7         7    G    11
3        4    D     8         8    H    12

In [27]:
df1 = pd.DataFrame({'ID':[1,2,3,4],
              'Name':['A','B','C','D'],
              'Class':[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [28]:
df2 = pd.DataFrame({'Marks':[40,63,91,34]})
df2

   Marks
0     40
1     63
2     91
3     34

In [29]:
pd.concat([df1,df2])

    ID Name  Class  Marks
0  1.0    A    5.0    NaN
1  2.0    B    6.0    NaN
2  3.0    C    7.0    NaN
3  4.0    D    8.0    NaN
0  NaN  NaN    NaN   40.0
1  NaN  NaN    NaN   63.0
2  NaN  NaN    NaN   91.0
3  NaN  NaN    NaN   34.0