Pandas Replace () :

In [316]:
import pandas as pd
import numpy as np

In [337]:
df=pd.read_csv("C:\\Users\\ajayr\\Downloads\\customers-100.csv")
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [318]:
df.replace(to_replace='East Leonard', value='Mumbai')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Mumbai,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,Mumbai,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Mumbai,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Mumbai,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,Mumbai,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Mumbai,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Mumbai,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Mumbai,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [319]:
df.replace(to_replace='East Leonard', value='Nagpur')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Nagpur,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,Nagpur,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Nagpur,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Nagpur,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,Nagpur,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Nagpur,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Nagpur,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Nagpur,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [320]:
df.replace('East Leonard', 'Mumbai')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Mumbai,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,Mumbai,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Mumbai,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Mumbai,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,Mumbai,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Mumbai,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Mumbai,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Mumbai,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [321]:
df.replace(4, 11)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,11,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [322]:
df.replace([1,2,3,4,5,6,6,7,8,9,10], 0)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,0,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,0,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,0,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,0,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [323]:
df.replace([1,2,3,4,5,6,6,7,8,9,10], [11,12,13,14,15,16,17,18,19,20,21])

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,11,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,12,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,13,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,14,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,15,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [324]:
df.replace({'Country': 'Chile'}, 'None')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,None,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,None,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,None,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,None,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,None,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,None,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,None,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,None,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,None,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [325]:
df.replace({'Country': 'Chile','City': 'East Leonard'}, 'None')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,None,None,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,None,None,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,None,None,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",None,None,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,None,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,None,None,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,None,None,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,None,None,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",None,None,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [326]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [327]:
df.replace('[A-Za-z]',0)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [328]:
df.replace( '[A-Za-z]',0, regex=True)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,0,0,0,0,0,0,229.077.5154,0,0,24-08-2020,0
1,2,0,0,0,0,0,0,5153435776,0,0,23-04-2021,0
2,3,0,0,0,0,0,0,-1199,0,0,25-03-2020,0
3,4,0,0,0,0,0,0,0,-9892,0,02-06-2020,0
4,5,0,0,0,0,0,0,0,0,0,17-04-2021,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,0,0,0,0,0,0,0,0,30-01-2022,0
96,97,0,0,0,0,0,0,-3769,605.413.3198,0,10-07-2021,0
97,98,0,0,0,0,0,0,0,0,0,18-09-2021,0
98,99,0,0,0,0,0,0,(530)311-9786,0,0,11-08-2021,0
99,100,0,0,0,0,0,0,(753)813-6941,783.639.1472,0,11-03-2020,0

In [338]:
df['Last Name']= df['Last Name'].replace( r'[A-Za-z]', 0, regex=True)
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,0,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,0,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,0,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,0,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,0,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,0,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,0,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,0,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,0,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [339]:
df.replace({'Last Name': '[A-Za-z]'}, 0, regex=True)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,0,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,0,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,0,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,0,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,0,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,0,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,0,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,0,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,0,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [340]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,0,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,0,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,0,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,0,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,0,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,0,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,0,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,0,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,0,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [341]:
df.replace('East Leonard', 'Mumbai').ffill()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,0,Rasmussen Group,Mumbai,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,0,Vega-Gentry,Mumbai,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,0,Murillo-Perry,Mumbai,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,0,"Dominguez, Mcmillan and Donovan",Mumbai,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,0,Carey LLC,Mumbai,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,0,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,0,Schmitt-Jones,Mumbai,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,0,Fitzgerald-Harrell,Mumbai,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,0,"Le, Nash and Cross",Mumbai,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [342]:
df.replace('East Leonard',None ).bfill()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,0,Rasmussen Group,West Priscilla,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,0,Vega-Gentry,West Priscilla,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,0,Murillo-Perry,West Priscilla,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,0,"Dominguez, Mcmillan and Donovan",West Priscilla,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,0,Carey LLC,New Bradview,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,0,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,0,Schmitt-Jones,NaN,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,0,Fitzgerald-Harrell,NaN,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,0,"Le, Nash and Cross",NaN,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [343]:
df.replace(0,None).bfill(limit=10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,None,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,None,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,None,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,None,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,None,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,None,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,None,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,None,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,None,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,None,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [344]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,0,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,0,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,0,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,0,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,0,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,0,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,0,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,0,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,0,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [345]:
df.replace(0,100, inplace=True)
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,100,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,100,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,100,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,100,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,100,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,100,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,100,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,100,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,100,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,100,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [346]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,100,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,100,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,100,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,100,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,100,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,100,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,100,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,100,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,100,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,100,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [347]:
df.replace(0,100, inplace=True)
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,100,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,100,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,100,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,100,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,100,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,100,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,100,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,100,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,100,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,100,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/