# Pandas Pivot_Table() :

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\Diabetes Missing Data.csv")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [8]:
df.pivot_table(index='Pregnant')

,Age,BMI,Class,Diabetes_Pedigree,Diastolic_BP,Glucose,Serum_Insulin,Skin_Fold
Pregnant,,,,,,,,
0.0,27.603604,35.242593,0.342342,0.520838,73.801980,123.000000,159.052632,31.291139
1.0,27.370370,31.372593,0.214815,0.486496,68.298507,115.310606,141.712766,27.722689
2.0,27.194175,31.189109,0.184466,0.491660,67.864583,110.796117,138.156250,27.812500
3.0,29.026667,30.836486,0.360000,0.432147,69.361111,123.586667,145.755556,26.421053
4.0,32.820896,32.059701,0.343284,0.450164,72.968750,125.343284,174.888889,26.341463
5.0,39.035088,33.785714,0.368421,0.396421,76.210526,120.982143,155.523810,30.968750
6.0,39.340000,30.908163,0.320000,0.429520,72.787234,123.265306,167.315789,30.413793
7.0,41.111111,33.372727,0.555556,0.443622,75.833333,136.444444,190.050000,31.482759
8.0,45.368421,32.421622,0.578947,0.504711,77.216216,131.736842,251.928571,32.900000
9.0,44.178571,31.707143,0.642857,0.550679,77.892857,131.392857,158.909091,30.789474
10.0,42.666667,31.973913,0.416667,0.454167,76.590909,120.916667,139.166667,31.416667
11.0,44.545455,38.563636,0.636364,0.522545,81.600000,126.454545,144.000000,34.142857
12.0,47.444444,32.344444,0.444444,0.444333,76.333333,113.555556,202.600000,30.500000
13.0,44.500000,35.000000,0.500000,0.463300,82.000000,125.500000,93.000000,34.600000
14.0,42.000000,35.100000,1.000000,0.312000,70.000000,137.500000,184.000000,27.500000
15.0,43.000000,37.100000,1.000000,0.153000,70.000000,136.000000,110.000000,32.000000
17.0,47.000000,40.900000,1.000000,0.817000,72.000000,163.000000,114.000000,41.000000

In [9]:
df.pivot_table(index='Pregnant', columns='Skin_Fold')

            Age                                                            \
Skin_Fold  7.0   8.0   10.0  11.0       12.0  13.0  14.0       15.0  16.0
Pregnant
0.0         NaN   NaN  22.0   NaN        NaN  21.0  21.5  22.000000  21.0
1.0         NaN  28.5  21.0  22.0  26.666667  23.4  21.0  23.750000  24.0
2.0         NaN   NaN  22.0   NaN        NaN  24.5  23.0  23.000000  26.0
3.0         NaN   NaN  25.0  26.0  29.000000  23.0   NaN  40.333333  30.0
4.0         NaN   NaN   NaN  28.0  32.666667   NaN  33.0  27.500000   NaN
5.0         NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
6.0        60.0   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
7.0         NaN   NaN   NaN   NaN        NaN   NaN   NaN  37.000000   NaN
8.0         NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
9.0         NaN   NaN   NaN   NaN        NaN   NaN   NaN  49.000000   NaN
10.0        NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
11.0        NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
12.0       44.0   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
13.0        NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
14.0        NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
15.0        NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN
17.0        NaN   NaN   NaN   NaN        NaN   NaN   NaN        NaN   NaN

                 ... Serum_Insulin                                           \
Skin_Fold  17.0  ...          46.0   47.0   48.0   49.0   50.0   51.0  52.0
Pregnant         ...
0.0        23.0  ...    117.666667  230.0    NaN    NaN    NaN    NaN   NaN
1.0        27.5  ...    179.000000   63.0  200.0  579.0  124.5  220.0  65.0
2.0        23.0  ...           NaN    NaN    NaN    NaN  140.0    NaN  57.0
3.0         NaN  ...           NaN    NaN  465.0  155.0    NaN    NaN   NaN
4.0        27.0  ...           NaN  130.5    NaN    NaN    NaN    NaN   NaN
5.0         NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
6.0         NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
7.0        31.0  ...           NaN    NaN    NaN  125.0    NaN    NaN   NaN
8.0         NaN  ...    231.000000    NaN    NaN    NaN    NaN    NaN   NaN
9.0         NaN  ...    130.000000    NaN    NaN    NaN    NaN    NaN   NaN
10.0        NaN  ...           NaN    NaN  208.5    NaN    NaN    NaN   NaN
11.0        NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
12.0       62.0  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
13.0        NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
14.0        NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
15.0        NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN
17.0        NaN  ...           NaN    NaN    NaN    NaN    NaN    NaN   NaN


Skin_Fold   56.0   60.0  63.0
Pregnant
0.0        100.0  110.0  14.0
1.0          NaN    NaN   NaN
2.0          NaN    NaN   NaN
3.0          NaN    NaN   NaN
4.0          NaN    NaN   NaN
5.0          NaN    NaN   NaN
6.0          NaN    NaN   NaN
7.0          NaN    NaN   NaN
8.0          NaN    NaN   NaN
9.0          NaN    NaN   NaN
10.0         NaN    NaN   NaN
11.0         NaN    NaN   NaN
12.0         NaN    NaN   NaN
13.0         NaN    NaN   NaN
14.0         NaN    NaN   NaN
15.0         NaN    NaN   NaN
17.0         NaN    NaN   NaN

[17 rows x 348 columns]

In [ ]:
df.pivot_table(index='Pregnant', columns='Skin_Fold', aggfunc= 'count')

           Age                                               ...  \
Skin_Fold 7.0  8.0  10.0 11.0 12.0 13.0 14.0 15.0 16.0 17.0  ...
Pregnant                                                     ...
0.0        NaN  NaN  1.0  NaN  NaN  1.0  2.0  1.0  1.0  3.0  ...
1.0        NaN  2.0  2.0  3.0  3.0  5.0  1.0  4.0  1.0  2.0  ...
2.0        NaN  NaN  1.0  NaN  NaN  2.0  2.0  2.0  2.0  5.0  ...
3.0        NaN  NaN  1.0  2.0  1.0  3.0  NaN  3.0  2.0  NaN  ...
4.0        NaN  NaN  NaN  1.0  3.0  NaN  1.0  2.0  NaN  2.0  ...
5.0        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
6.0        1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
7.0        NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  ...
8.0        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
9.0        NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  ...
10.0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
11.0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
12.0       1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  ...
13.0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
14.0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
15.0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
17.0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...

          Serum_Insulin
Skin_Fold          48.0 49.0 50.0 51.0 52.0 54.0 56.0 60.0 63.0 99.0
Pregnant
0.0                 NaN  NaN  NaN  NaN  NaN  0.0  1.0  1.0  1.0  NaN
1.0                 1.0  1.0  2.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN
2.0                 NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  0.0
3.0                 1.0  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4.0                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5.0                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6.0                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7.0                 NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8.0                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9.0                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10.0                2.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
11.0                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
12.0                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
13.0                NaN  NaN  NaN  NaN  NaN  0.0  NaN  NaN  NaN  NaN
14.0                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
15.0                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
17.0                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[17 rows x 350 columns]

In [12]:
df.pivot_table(index='Pregnant', columns='Skin_Fold', aggfunc= 'max')

            Age                                                        ...  \
Skin_Fold  7.0   8.0   10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  ...
Pregnant                                                               ...
0.0         NaN   NaN  22.0   NaN   NaN  21.0  22.0  22.0  21.0  27.0  ...
1.0         NaN  36.0  21.0  22.0  28.0  25.0  21.0  26.0  24.0  33.0  ...
2.0         NaN   NaN  22.0   NaN   NaN  26.0  24.0  25.0  27.0  27.0  ...
3.0         NaN   NaN  25.0  30.0  29.0  24.0   NaN  63.0  38.0   NaN  ...
4.0         NaN   NaN   NaN  28.0  37.0   NaN  33.0  34.0   NaN  28.0  ...
5.0         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
6.0        60.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
7.0         NaN   NaN   NaN   NaN   NaN   NaN   NaN  37.0   NaN  31.0  ...
8.0         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
9.0         NaN   NaN   NaN   NaN   NaN   NaN   NaN  49.0   NaN   NaN  ...
10.0        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
11.0        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
12.0       44.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  62.0  ...
13.0        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
14.0        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
15.0        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
17.0        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...

          Serum_Insulin                                                  \
Skin_Fold          46.0   47.0   48.0   49.0   50.0   51.0  52.0   56.0
Pregnant
0.0               145.0  230.0    NaN    NaN    NaN    NaN   NaN  100.0
1.0               180.0   63.0  200.0  579.0  204.0  220.0  65.0    NaN
2.0                 NaN    NaN    NaN    NaN  140.0    NaN  57.0    NaN
3.0                 NaN    NaN  465.0  155.0    NaN    NaN   NaN    NaN
4.0                 NaN  207.0    NaN    NaN    NaN    NaN   NaN    NaN
5.0                 NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
6.0                 NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
7.0                 NaN    NaN    NaN  125.0    NaN    NaN   NaN    NaN
8.0               231.0    NaN    NaN    NaN    NaN    NaN   NaN    NaN
9.0               130.0    NaN    NaN    NaN    NaN    NaN   NaN    NaN
10.0                NaN    NaN  237.0    NaN    NaN    NaN   NaN    NaN
11.0                NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
12.0                NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
13.0                NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
14.0                NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
15.0                NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN
17.0                NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN


Skin_Fold   60.0  63.0
Pregnant
0.0        110.0  14.0
1.0          NaN   NaN
2.0          NaN   NaN
3.0          NaN   NaN
4.0          NaN   NaN
5.0          NaN   NaN
6.0          NaN   NaN
7.0          NaN   NaN
8.0          NaN   NaN
9.0          NaN   NaN
10.0         NaN   NaN
11.0         NaN   NaN
12.0         NaN   NaN
13.0         NaN   NaN
14.0         NaN   NaN
15.0         NaN   NaN
17.0         NaN   NaN

[17 rows x 348 columns]

In [13]:
df.pivot_table(index='Pregnant', columns='Skin_Fold', aggfunc= 'sum')

            Age                                                           ...  \
Skin_Fold  7.0   8.0   10.0  11.0  12.0   13.0  14.0   15.0  16.0   17.0  ...
Pregnant                                                                  ...
0.0         NaN   NaN  22.0   NaN   NaN   21.0  43.0   22.0  21.0   69.0  ...
1.0         NaN  57.0  42.0  66.0  80.0  117.0  21.0   95.0  24.0   55.0  ...
2.0         NaN   NaN  22.0   NaN   NaN   49.0  46.0   46.0  52.0  115.0  ...
3.0         NaN   NaN  25.0  52.0  29.0   69.0   NaN  121.0  60.0    NaN  ...
4.0         NaN   NaN   NaN  28.0  98.0    NaN  33.0   55.0   NaN   54.0  ...
5.0         NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
6.0        60.0   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
7.0         NaN   NaN   NaN   NaN   NaN    NaN   NaN   37.0   NaN   31.0  ...
8.0         NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
9.0         NaN   NaN   NaN   NaN   NaN    NaN   NaN   49.0   NaN    NaN  ...
10.0        NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
11.0        NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
12.0       44.0   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN   62.0  ...
13.0        NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
14.0        NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
15.0        NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...
17.0        NaN   NaN   NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...

          Serum_Insulin                                                      \
Skin_Fold          48.0   49.0   50.0   51.0  52.0 54.0   56.0   60.0  63.0
Pregnant
0.0                 NaN    NaN    NaN    NaN   NaN  0.0  100.0  110.0  14.0
1.0               200.0  579.0  249.0  220.0  65.0  NaN    NaN    NaN   NaN
2.0                 NaN    NaN  140.0    NaN  57.0  NaN    NaN    NaN   NaN
3.0               465.0  155.0    NaN    NaN   NaN  NaN    NaN    NaN   NaN
4.0                 NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
5.0                 NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
6.0                 NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
7.0                 NaN  125.0    NaN    NaN   NaN  NaN    NaN    NaN   NaN
8.0                 NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
9.0                 NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
10.0              417.0    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
11.0                NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
12.0                NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
13.0                NaN    NaN    NaN    NaN   NaN  0.0    NaN    NaN   NaN
14.0                NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
15.0                NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN
17.0                NaN    NaN    NaN    NaN   NaN  NaN    NaN    NaN   NaN


Skin_Fold 99.0
Pregnant
0.0        NaN
1.0        NaN
2.0        0.0
3.0        NaN
4.0        NaN
5.0        NaN
6.0        NaN
7.0        NaN
8.0        NaN
9.0        NaN
10.0       NaN
11.0       NaN
12.0       NaN
13.0       NaN
14.0       NaN
15.0       NaN
17.0       NaN

[17 rows x 350 columns]

In [15]:
df.pivot_table(index='Pregnant', columns='Skin_Fold', fill_value=0)

            Age                                                            \
Skin_Fold  7.0   8.0   10.0  11.0       12.0  13.0  14.0       15.0  16.0
Pregnant
0.0         0.0   0.0  22.0   0.0   0.000000  21.0  21.5  22.000000  21.0
1.0         0.0  28.5  21.0  22.0  26.666667  23.4  21.0  23.750000  24.0
2.0         0.0   0.0  22.0   0.0   0.000000  24.5  23.0  23.000000  26.0
3.0         0.0   0.0  25.0  26.0  29.000000  23.0   0.0  40.333333  30.0
4.0         0.0   0.0   0.0  28.0  32.666667   0.0  33.0  27.500000   0.0
5.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
6.0        60.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
7.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.0  37.000000   0.0
8.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
9.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.0  49.000000   0.0
10.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
11.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
12.0       44.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
13.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
14.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
15.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0
17.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.0   0.000000   0.0

                 ... Serum_Insulin                                         \
Skin_Fold  17.0  ...          48.0   49.0   50.0   51.0  52.0 54.0   56.0
Pregnant         ...
0.0        23.0  ...           0.0    0.0    0.0    0.0   0.0  0.0  100.0
1.0        27.5  ...         200.0  579.0  124.5  220.0  65.0  0.0    0.0
2.0        23.0  ...           0.0    0.0  140.0    0.0  57.0  0.0    0.0
3.0         0.0  ...         465.0  155.0    0.0    0.0   0.0  0.0    0.0
4.0        27.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
5.0         0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
6.0         0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
7.0        31.0  ...           0.0  125.0    0.0    0.0   0.0  0.0    0.0
8.0         0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
9.0         0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
10.0        0.0  ...         208.5    0.0    0.0    0.0   0.0  0.0    0.0
11.0        0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
12.0       62.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
13.0        0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
14.0        0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
15.0        0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0
17.0        0.0  ...           0.0    0.0    0.0    0.0   0.0  0.0    0.0


Skin_Fold   60.0  63.0 99.0
Pregnant
0.0        110.0  14.0  0.0
1.0          0.0   0.0  0.0
2.0          0.0   0.0  0.0
3.0          0.0   0.0  0.0
4.0          0.0   0.0  0.0
5.0          0.0   0.0  0.0
6.0          0.0   0.0  0.0
7.0          0.0   0.0  0.0
8.0          0.0   0.0  0.0
9.0          0.0   0.0  0.0
10.0         0.0   0.0  0.0
11.0         0.0   0.0  0.0
12.0         0.0   0.0  0.0
13.0         0.0   0.0  0.0
14.0         0.0   0.0  0.0
15.0         0.0   0.0  0.0
17.0         0.0   0.0  0.0

[17 rows x 350 columns]

In [16]:
df.pivot_table(index='Pregnant', columns='Skin_Fold', fill_value=0, margins= True)

            Age                                                           \
Skin_Fold   7.0   8.0  10.0  11.0       12.0  13.0       14.0       15.0
Pregnant
0.0         0.0   0.0  22.0   0.0   0.000000  21.0  21.500000  22.000000
1.0         0.0  28.5  21.0  22.0  26.666667  23.4  21.000000  23.750000
2.0         0.0   0.0  22.0   0.0   0.000000  24.5  23.000000  23.000000
3.0         0.0   0.0  25.0  26.0  29.000000  23.0   0.000000  40.333333
4.0         0.0   0.0   0.0  28.0  32.666667   0.0  33.000000  27.500000
5.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
6.0        60.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
7.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.000000  37.000000
8.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
9.0         0.0   0.0   0.0   0.0   0.000000   0.0   0.000000  49.000000
10.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
11.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
12.0       44.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
13.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
14.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
15.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
17.0        0.0   0.0   0.0   0.0   0.000000   0.0   0.000000   0.000000
All        52.0  21.0  23.0  24.8  29.500000  23.4  23.833333  26.545455

                       ... Serum_Insulin                                       \
Skin_Fold  16.0  17.0  ...          49.0        50.0   51.0  52.0 54.0   56.0
Pregnant               ...
0.0        21.0  23.0  ...      0.000000    0.000000    0.0   0.0  0.0  100.0
1.0        24.0  27.5  ...    579.000000  124.500000  220.0  65.0  0.0    0.0
2.0        26.0  23.0  ...      0.000000  140.000000    0.0  57.0  0.0    0.0
3.0        30.0   0.0  ...    155.000000    0.000000    0.0   0.0  0.0    0.0
4.0         0.0  27.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
5.0         0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
6.0         0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
7.0         0.0  31.0  ...    125.000000    0.000000    0.0   0.0  0.0    0.0
8.0         0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
9.0         0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
10.0        0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
11.0        0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
12.0        0.0  62.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
13.0        0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
14.0        0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
15.0        0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
17.0        0.0   0.0  ...      0.000000    0.000000    0.0   0.0  0.0    0.0
All        27.2  25.3  ...    286.333333  129.666667  220.0  61.0  0.0  100.0


Skin_Fold   60.0  63.0 99.0         All
Pregnant
0.0        110.0  14.0  0.0  160.303571
1.0          0.0   0.0  0.0  142.989247
2.0          0.0   0.0  0.0  138.156250
3.0          0.0   0.0  0.0  145.755556
4.0          0.0   0.0  0.0  174.888889
5.0          0.0   0.0  0.0  155.523810
6.0          0.0   0.0  0.0  167.315789
7.0          0.0   0.0  0.0  190.050000
8.0          0.0   0.0  0.0  251.928571
9.0          0.0   0.0  0.0  158.909091
10.0         0.0   0.0  0.0  139.166667
11.0         0.0   0.0  0.0  144.000000
12.0         0.0   0.0  0.0  202.600000
13.0         0.0   0.0  0.0   93.000000
14.0         0.0   0.0  0.0  184.000000
15.0         0.0   0.0  0.0  110.000000
17.0         0.0   0.0  0.0  114.000000
All        110.0  14.0  0.0  156.056122

[18 rows x 357 columns]

In [17]:
df.pivot_table(index='Pregnant', columns='Skin_Fold', aggfunc='sum',fill_value=0, margins= True)

             Age                                                               \
Skin_Fold    7.0   8.0  10.0   11.0   12.0   13.0   14.0   15.0   16.0   17.0
Pregnant
0.0          0.0   0.0  22.0    0.0    0.0   21.0   43.0   22.0   21.0   69.0
1.0          0.0  57.0  42.0   66.0   80.0  117.0   21.0   95.0   24.0   55.0
2.0          0.0   0.0  22.0    0.0    0.0   49.0   46.0   46.0   52.0  115.0
3.0          0.0   0.0  25.0   52.0   29.0   69.0    0.0  121.0   60.0    0.0
4.0          0.0   0.0   0.0   28.0   98.0    0.0   33.0   55.0    0.0   54.0
5.0          0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6.0         60.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
7.0          0.0   0.0   0.0    0.0    0.0    0.0    0.0   37.0    0.0   31.0
8.0          0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
9.0          0.0   0.0   0.0    0.0    0.0    0.0    0.0   49.0    0.0    0.0
10.0         0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
11.0         0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
12.0        44.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0   62.0
13.0         0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
14.0         0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
15.0         0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
17.0         0.0   0.0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
All        104.0  21.0  69.0  124.0  177.0  234.0  143.0  292.0  136.0  253.0

           ... Serum_Insulin                                                \
Skin_Fold  ...          49.0   50.0   51.0   52.0 54.0   56.0   60.0  63.0
Pregnant   ...
0.0        ...           0.0    0.0    0.0    0.0  0.0  100.0  110.0  14.0
1.0        ...         579.0  249.0  220.0   65.0  0.0    0.0    0.0   0.0
2.0        ...           0.0  140.0    0.0   57.0  0.0    0.0    0.0   0.0
3.0        ...         155.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
4.0        ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
5.0        ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
6.0        ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
7.0        ...         125.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
8.0        ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
9.0        ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
10.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
11.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
12.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
13.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
14.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
15.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
17.0       ...           0.0    0.0    0.0    0.0  0.0    0.0    0.0   0.0
All        ...         859.0  389.0  220.0  122.0  0.0  100.0  110.0  14.0


Skin_Fold 99.0      All
Pregnant
0.0        0.0   8977.0
1.0        0.0  13298.0
2.0        0.0   8842.0
3.0        0.0   6559.0
4.0        0.0   4722.0
5.0        0.0   3266.0
6.0        0.0   3179.0
7.0        0.0   3801.0
8.0        0.0   3527.0
9.0        0.0   1748.0
10.0       0.0    835.0
11.0       0.0    720.0
12.0       0.0   1013.0
13.0       0.0    279.0
14.0       0.0    184.0
15.0       0.0    110.0
17.0       0.0    114.0
All        0.0  61174.0

[18 rows x 357 columns]