# Pandas Interpolate() :

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv")
df

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4      NaN  20.0
4    5   4300.0   NaN
5    6      NaN  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30      NaN  33.0
30  31  47000.0  54.0

In [3]:
df.interpolate()

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4   4650.0  20.0
4    5   4300.0  26.5
5    6  12150.0  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11  30500.0  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0  44.0
15  16  34000.0  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23  17500.0  56.0
23  24  23000.0  46.5
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27  23000.0  62.0
27  28  29000.0  57.0
28  29  35000.0  51.0
29  30  41000.0  33.0
30  31  47000.0  54.0

In [4]:
type(df.ID[0])

numpy.int64

In [5]:
df.interpolate(method='linear')

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4   4650.0  20.0
4    5   4300.0  26.5
5    6  12150.0  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11  30500.0  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0  44.0
15  16  34000.0  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23  17500.0  56.0
23  24  23000.0  46.5
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27  23000.0  62.0
27  28  29000.0  57.0
28  29  35000.0  51.0
29  30  41000.0  33.0
30  31  47000.0  54.0

In [6]:
df = pd.read_csv('C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv', parse_dates=['ID'])
df

C:\Users\ajayr\AppData\Local\Temp\ipykernel_17560\1227813056.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv', parse_dates=['ID'])

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4      NaN  20.0
4    5   4300.0   NaN
5    6      NaN  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30      NaN  33.0
30  31  47000.0  54.0

In [7]:
type(df.ID[0])

str

In [8]:
df = pd.read_csv('C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv', parse_dates=['ID'], index_col ='ID')
df

C:\Users\ajayr\AppData\Local\Temp\ipykernel_17560\900441089.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv', parse_dates=['ID'], index_col ='ID')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4       NaN  20.0
5    4300.0   NaN
6       NaN  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11      NaN  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0   NaN
16      NaN  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23      NaN  56.0
24  23000.0   NaN
25  16000.0  37.0
26  17000.0  49.0
27      NaN  62.0
28      NaN  57.0
29  35000.0  51.0
30      NaN  33.0
31  47000.0  54.0

In [9]:
df.interpolate(method='index')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28  29000.0  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [10]:
df.interpolate(method='nearest')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    5000.0  20.0
5    4300.0  20.0
6    4300.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  29000.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  56.0
16   7000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  12000.0  56.0
24  23000.0  56.0
25  16000.0  37.0
26  17000.0  49.0
27  17000.0  62.0
28  35000.0  57.0
29  35000.0  51.0
30  35000.0  33.0
31  47000.0  54.0

In [11]:
df.interpolate(method='polynomial', order =2)

          Income        Age
ID
1   10000.000000  22.000000
2   13000.000000  30.000000
3    5000.000000  19.000000
4    2265.512044  20.000000
5    4300.000000  22.292675
6    7896.009060  33.000000
7   20000.000000  51.000000
8   43000.000000  28.000000
9   48000.000000  45.000000
10  29000.000000  44.000000
11  31439.863541  31.000000
12  32000.000000  23.000000
13   9000.000000  12.000000
14  11000.000000  56.000000
15   7000.000000  51.472904
16  43287.412737  32.000000
17  61000.000000  45.000000
18  18000.000000  52.000000
19  43000.000000  32.000000
20  30000.000000  45.000000
21  70000.000000  78.000000
22  12000.000000  43.000000
23   4873.511885  56.000000
24  23000.000000  48.719610
25  16000.000000  37.000000
26  17000.000000  49.000000
27  21804.674085  62.000000
28  28433.792988  57.000000
29  35000.000000  51.000000
30  41188.735671  33.000000
31  47000.000000  54.000000

In [12]:
df.interpolate(method='spline', order = 2)

          Income        Age
ID
1   10000.000000  22.000000
2   13000.000000  30.000000
3    5000.000000  19.000000
4    2265.542456  20.000000
5    4300.000000  22.927379
6    7896.009504  33.000000
7   20000.000000  51.000000
8   43000.000000  28.000000
9   48000.000000  45.000000
10  29000.000000  44.000000
11  31439.647265  31.000000
12  32000.000000  23.000000
13   9000.000000  12.000000
14  11000.000000  56.000000
15   7000.000000  50.513891
16  43286.755426  32.000000
17  61000.000000  45.000000
18  18000.000000  52.000000
19  43000.000000  32.000000
20  30000.000000  45.000000
21  70000.000000  78.000000
22  12000.000000  43.000000
23   4874.561267  56.000000
24  23000.000000  47.485428
25  16000.000000  37.000000
26  17000.000000  49.000000
27  21804.313675  62.000000
28  28433.631006  57.000000
29  35000.000000  51.000000
30  41188.794518  33.000000
31  47000.000000  54.000000

In [13]:
df

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4       NaN  20.0
5    4300.0   NaN
6       NaN  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11      NaN  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0   NaN
16      NaN  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23      NaN  56.0
24  23000.0   NaN
25  16000.0  37.0
26  17000.0  49.0
27      NaN  62.0
28      NaN  57.0
29  35000.0  51.0
30      NaN  33.0
31  47000.0  54.0

In [14]:
df.interpolate()

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28  29000.0  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [15]:
df.dtypes

Income    float64
Age       float64
dtype: object

In [16]:
df.interpolate(limit=1)

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28      NaN  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [17]:
df.interpolate(limit=2)

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28  29000.0  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [21]:
df

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4       NaN  20.0
5    4300.0   NaN
6       NaN  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11      NaN  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0   NaN
16      NaN  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23      NaN  56.0
24  23000.0   NaN
25  16000.0  37.0
26  17000.0  49.0
27      NaN  62.0
28      NaN  57.0
29  35000.0  51.0
30      NaN  33.0
31  47000.0  54.0

In [22]:
df.interpolate(limit=1,limit_ditection= 'backward')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28      NaN  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [23]:
df.interpolate(limit=1,limit_ditection= 'both')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28      NaN  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [24]:
df.interpolate(limit_area='inside')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28  29000.0  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [25]:
df.interpolate(limit_area='outside')

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4       NaN  20.0
5    4300.0   NaN
6       NaN  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11      NaN  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0   NaN
16      NaN  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23      NaN  56.0
24  23000.0   NaN
25  16000.0  37.0
26  17000.0  49.0
27      NaN  62.0
28      NaN  57.0
29  35000.0  51.0
30      NaN  33.0
31  47000.0  54.0

In [26]:
df

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4       NaN  20.0
5    4300.0   NaN
6       NaN  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11      NaN  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0   NaN
16      NaN  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23      NaN  56.0
24  23000.0   NaN
25  16000.0  37.0
26  17000.0  49.0
27      NaN  62.0
28      NaN  57.0
29  35000.0  51.0
30      NaN  33.0
31  47000.0  54.0

In [27]:
df.interpolate(inplace=True)
df

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28  29000.0  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0

In [28]:
df

     Income   Age
ID
1   10000.0  22.0
2   13000.0  30.0
3    5000.0  19.0
4    4650.0  20.0
5    4300.0  26.5
6   12150.0  33.0
7   20000.0  51.0
8   43000.0  28.0
9   48000.0  45.0
10  29000.0  44.0
11  30500.0  31.0
12  32000.0  23.0
13   9000.0  12.0
14  11000.0  56.0
15   7000.0  44.0
16  34000.0  32.0
17  61000.0  45.0
18  18000.0  52.0
19  43000.0  32.0
20  30000.0  45.0
21  70000.0  78.0
22  12000.0  43.0
23  17500.0  56.0
24  23000.0  46.5
25  16000.0  37.0
26  17000.0  49.0
27  23000.0  62.0
28  29000.0  57.0
29  35000.0  51.0
30  41000.0  33.0
31  47000.0  54.0