# Pandas Join() or Append() --> Replacement of Concat() :

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'A':[1,2,3,4],
                    'B':[10,20,30,40]})
df2 =pd.DataFrame({'A':[5,6,7,8],
                   'B':[50,60,70,80]})
display(df1,df2)

   A   B
0  1  10
1  2  20
2  3  30
3  4  40

   A   B
0  5  50
1  6  60
2  7  70
3  8  80

In [12]:
pd.concat([df1,df2])

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
0  5  50
1  6  60
2  7  70
3  8  80

In [11]:
pd.concat([df1,df2], ignore_index= True)

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  60
6  7  70
7  8  80

In [14]:
pd.concat([df1, df2], ignore_index=True, sort=False)

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  60
6  7  70
7  8  80