# Pandas Join() :

In [1]:

import pandas as pd

In [4]:
df1 =pd.DataFrame({'A':[1,2,3],
                   'B':[10,20,30]})

df2 =pd.DataFrame({'C':[4,5,6],
                   'D':[40,50,60,]})

display(df1,df2)

   A   B
0  1  10
1  2  20
2  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [5]:
df1.join(df2)

   A   B  C   D
0  1  10  4  40
1  2  20  5  50
2  3  30  6  60

In [6]:
df2.join(df1)

   C   D  A   B
0  4  40  1  10
1  5  50  2  20
2  6  60  3  30

In [7]:
df3 =pd.DataFrame({'A':[1,2,3],
                   'B':[10,20,30]}, index =['a','b','c'])

df4 =pd.DataFrame({'C':[4,5,6],
                   'D':[40,50,60,]})

display(df3,df4)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [8]:
df3.join(df4)

   A   B   C   D
a  1  10 NaN NaN
b  2  20 NaN NaN
c  3  30 NaN NaN

In [9]:
df3 =pd.DataFrame({'A':[1,2,3],
                   'B':[10,20,30]}, index =['a','b','c'])

df4 =pd.DataFrame({'C':[4,5,6],
                   'D':[40,50,60,]}, index =['a','b','c'])

display(df3,df4)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
a  4  40
b  5  50
c  6  60

In [10]:
df3.join(df4)

   A   B  C   D
a  1  10  4  40
b  2  20  5  50
c  3  30  6  60

In [12]:
df3 =pd.DataFrame({'A':[1,2,3],
                   'B':[10,20,30]}, index =['a','b','c'])

df4 =pd.DataFrame({'C':[4,5],
                   'D':[40,50]}, index =['a','b'])

display(df3,df4)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
a  4  40
b  5  50

In [13]:
df3.join(df4)

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

In [14]:
df3.join(df4, how = 'right')

   A   B  C   D
a  1  10  4  40
b  2  20  5  50

In [ ]:
df3.join(df4, how = 'left')

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

In [16]:
df3.join(df4, how = 'inner')

   A   B  C   D
a  1  10  4  40
b  2  20  5  50

In [18]:
df3.join(df4, how = 'outer')

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

In [19]:
df3 =pd.DataFrame({'A':[1,2,3],
                   'B':[10,20,30]}, index =['a','b','c'])

df4 =pd.DataFrame({'A':[4,5],
                   'D':[40,50]}, index =['a','b'])

display(df3,df4)

   A   B
a  1  10
b  2  20
c  3  30

   A   D
a  4  40
b  5  50

In [20]:
df3.join(df4, lsuffix = '_1')

   A_1   B    A     D
a    1  10  4.0  40.0
b    2  20  5.0  50.0
c    3  30  NaN   NaN

In [21]:
df3.join(df4, rsuffix = '_1')

   A   B  A_1     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN