## Pandas GroupBy () :

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\customers-100.csv")
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [17]:
gr1 = df.groupby(by= 'Company')
gr1

In [18]:
gr1.groups

{'Acosta, Petersen and Morrow': [30], 'Adkins-Salinas': [32], 'Anderson Ltd': [39], 'Beck-Hendrix': [9], 'Blankenship-Arias': [80], 'Brennan, Acosta and Ramos': [47], 'Brennan, Camacho and Tapia': [60], 'Browning-Simon': [8], 'Byrd Inc': [53], 'Byrd-Campbell': [90], 'Caldwell Group': [62], 'Carey LLC': [95], 'Carpenter-Cook': [13], 'Carter-Hancock': [14], 'Carter-Strickland': [88], 'Chang, Aguirre and Leblanc': [75], 'Christian, Winters and Ellis': [52], 'Church-Banks': [65], 'Coffey, Lamb and Johnson': [81], 'Combs, Waller and Durham': [79], 'Conway-Mcbride': [71], 'Costa PLC': [56], 'Cross PLC': [43], 'Decker-Mcknight': [89], 'Dominguez, Mcmillan and Donovan': [3], 'Donaldson-Dougherty': [67], 'Fitzgerald-Harrell': [98], 'Fitzpatrick-Lawrence': [82], 'Garcia-Jimenez': [83], 'Giles Ltd': [25], 'Glover and Sons': [37], 'Graham-Francis': [12], 'Greer and Sons': [22], 'Guzman-Brown': [74], 'Henderson Inc': [66], 'Herrera Group': [33], 'Herrera, Shepherd and Underwood': [44], 'Hinton, Chaney and Stokes': [27], 'Hobbs, Garrett and Sanford': [49], 'Hoffman, Reed and Mcclain': [11], 'Huerta-Mclean': [38], 'Huynh and Sons': [72], 'Jordan Ltd': [36], 'Kaufman and Sons': [41], 'Keller-Coffey': [70], 'Knight, Abbott and Hubbard': [64], 'Lamb-Peterson': [92], 'Le, Nash and Cross': [99], 'Lee, Lucero and Johnson': [93], 'Lester, Woodard and Mitchell': [6], 'Manning, Hester and Arroyo': [21], 'Martin, Lang and Andrade': [4], 'Mason-Hester': [76], 'May, Goodwin and Martin': [51], 'Mays-Mccormick': [19], 'Mcdonald, Bird and Ramirez': [84], 'Mcgee Group': [31], 'Mcguire, Huynh and Hopkins': [77], 'Monroe PLC': [40], 'Montes PLC': [55], 'Montoya-Miller': [86], 'Moore, Mccoy and Glass': [58], 'Murillo-Perry': [2], 'Newton, Petersen and Mathis': [94], 'Nixon, Blackwell and Sosa': [54], 'Novak LLC': [57], 'Oconnell, Meza and Everett': [10], 'Osborne-Erickson': [48], 'Palmer, Barnes and Houston': [35], 'Parrish Ltd': [73], 'Patterson Inc': [20], 'Perkins-Trevino': [42], 'Petty Ltd': [59], 'Phelps, Forbes and Koch': [50], 'Price, Sexton and Mcdaniel': [45], 'Prince, Malone and Pugh': [61], 'Rasmussen Group': [0], 'Rocha-Hart': [91], 'Sanchez, Marsh and Hale': [78], 'Sanford, Davenport and Giles': [7], 'Santana-Duran': [28], 'Sawyer PLC': [29], 'Schmitt-Jones': [97], 'Short-Wiggins': [46], 'Simmons Group': [26], 'Simon LLC': [18, 63], 'Singleton and Sons': [15], 'Steele Group': [5], 'Stephens Inc': [85], 'Tucker LLC': [24], 'Valentine LLC': [17], 'Vaughn, Watts and Leach': [87], 'Vega-Gentry': [1], 'Wade PLC': [69], 'Ware, Burns and Oneal': [96], 'Warren Ltd': [68], 'Waters, Chase and Aguilar': [34], 'Watts-Donaldson': [23], 'Winters-Mendoza': [16]}

In [19]:
df.groupby(['Country' ,'Company']).groups

{('Albania', 'Tucker LLC'): RangeIndex(start=24, stop=25, step=1),
 ('Algeria', 'May, Goodwin and Martin'): RangeIndex(start=51, stop=52, step=1),
 ('Bahamas',
  'Waters, Chase and Aguilar'): RangeIndex(start=34, stop=35, step=1),
 ('Belarus',
  'Hobbs, Garrett and Sanford'): RangeIndex(start=49, stop=50, step=1),
 ('Belarus', 'Simmons Group'): RangeIndex(start=26, stop=27, step=1),
 ('Belize',
  'Palmer, Barnes and Houston'): RangeIndex(start=35, stop=36, step=1),
 ('Benin', 'Vaughn, Watts and Leach'): RangeIndex(start=87, stop=88, step=1),
 ('Bolivia', 'Perkins-Trevino'): RangeIndex(start=42, stop=43, step=1),
 ('Bosnia and Herzegovina',
  'Steele Group'): RangeIndex(start=5, stop=6, step=1),
 ('Bulgaria', 'Cross PLC'): RangeIndex(start=43, stop=44, step=1),
 ('Bulgaria',
  'Sanford, Davenport and Giles'): RangeIndex(start=7, stop=8, step=1),
 ('Burkina Faso', 'Kaufman and Sons'): RangeIndex(start=41, stop=42, step=1),
 ('Canada', 'Phelps, Forbes and Koch'): RangeIndex(start=50, stop=51, step=1),
 ('Canada', 'Wade PLC'): RangeIndex(start=69, stop=70, step=1),
 ('Chile', 'Browning-Simon'): RangeIndex(start=8, stop=9, step=1),
 ('Chile', 'Byrd-Campbell'): RangeIndex(start=90, stop=91, step=1),
 ('Chile', 'Carey LLC'): RangeIndex(start=95, stop=96, step=1),
 ('Chile', 'Carter-Strickland'): RangeIndex(start=88, stop=89, step=1),
 ('Chile',
  'Dominguez, Mcmillan and Donovan'): RangeIndex(start=3, stop=4, step=1),
 ('Chile', 'Fitzgerald-Harrell'): RangeIndex(start=98, stop=99, step=1),
 ('Chile', 'Lamb-Peterson'): RangeIndex(start=92, stop=93, step=1),
 ('Chile', 'Le, Nash and Cross'): RangeIndex(start=99, stop=100, step=1),
 ('Chile',
  'Lester, Woodard and Mitchell'): RangeIndex(start=6, stop=7, step=1),
 ('Chile', 'Martin, Lang and Andrade'): RangeIndex(start=4, stop=5, step=1),
 ('Chile', 'Murillo-Perry'): RangeIndex(start=2, stop=3, step=1),
 ('Chile', 'Rasmussen Group'): RangeIndex(start=0, stop=1, step=1),
 ('Chile', 'Rocha-Hart'): RangeIndex(start=91, stop=92, step=1),
 ('Chile', 'Schmitt-Jones'): RangeIndex(start=97, stop=98, step=1),
 ('Chile', 'Vega-Gentry'): RangeIndex(start=1, stop=2, step=1),
 ('Denmark', 'Mcgee Group'): RangeIndex(start=31, stop=32, step=1),
 ('Dominica',
  'Sanchez, Marsh and Hale'): RangeIndex(start=78, stop=79, step=1),
 ('Dominican Republic', 'Monroe PLC'): RangeIndex(start=40, stop=41, step=1),
 ('Ecuador',
  'Nixon, Blackwell and Sosa'): RangeIndex(start=54, stop=55, step=1),
 ('Ethiopia', 'Caldwell Group'): RangeIndex(start=62, stop=63, step=1),
 ('Fiji', 'Mcdonald, Bird and Ramirez'): RangeIndex(start=84, stop=85, step=1),
 ('French Polynesia', 'Mays-Mccormick'): RangeIndex(start=19, stop=20, step=1),
 ('French Southern Territories',
  'Warren Ltd'): RangeIndex(start=68, stop=69, step=1),
 ('Ghana', 'Brennan, Acosta and Ramos'): RangeIndex(start=47, stop=48, step=1),
 ('Guernsey',
  'Oconnell, Meza and Everett'): RangeIndex(start=10, stop=11, step=1),
 ('Iceland',
  'Combs, Waller and Durham'): RangeIndex(start=79, stop=80, step=1),
 ('Iran', 'Keller-Coffey'): RangeIndex(start=70, stop=71, step=1),
 ('Isle of Man',
  'Fitzpatrick-Lawrence'): RangeIndex(start=82, stop=83, step=1),
 ('Kiribati', 'Donaldson-Dougherty'): RangeIndex(start=67, stop=68, step=1),
 ('Kyrgyz Republic', 'Mason-Hester'): RangeIndex(start=76, stop=77, step=1),
 ("Lao People's Democratic Republic",
  'Watts-Donaldson'): RangeIndex(start=23, stop=24, step=1),
 ('Liberia',
  'Knight, Abbott and Hubbard'): RangeIndex(start=64, stop=65, step=1),
 ('Liechtenstein', 'Adkins-Salinas'): RangeIndex(start=32, stop=33, step=1),
 ('Lithuania', 'Church-Banks'): RangeIndex(start=65, stop=66, step=1),
 ('Madagascar', 'Byrd Inc'): RangeIndex(start=53, stop=54, step=1),
 ('Maldives', 'Montoya-Miller'): RangeIndex(start=86, stop=87, step=1),
 ('Mali',
  'Newton, Petersen and Mathis'): RangeIndex(start=94, stop=95, step=1),
 ('Malta', 'Patterson Inc'): RangeIndex(start=20, stop=21, step=1),
 ('Micronesia', 'Blankenship-Arias'): RangeIndex(start=80, stop=81, step=1),
 ('Monaco',
  'Herrera, Shepherd and Underwood'): RangeIndex(start=44, stop=45, step=1),
 ('Montenegro', 'Huerta-Mclean'): RangeIndex(start=38, stop=39, step=1),
 ('Morocco', 'Conway-Mcbride'): RangeIndex(start=71, stop=72, step=1),
 ('Mozambique', 'Valentine LLC'): RangeIndex(start=17, stop=18, step=1),
 ('Myanmar',
  'Mcguire, Huynh and Hopkins'): RangeIndex(start=77, stop=78, step=1),
 ('Namibia', 'Decker-Mcknight'): RangeIndex(start=89, stop=90, step=1),
 ('Netherlands',
  'Manning, Hester and Arroyo'): RangeIndex(start=21, stop=22, step=1),
 ('Netherlands', 'Simon LLC'): RangeIndex(start=63, stop=64, step=1),
 ('New Caledonia', 'Henderson Inc'): RangeIndex(start=66, stop=67, step=1),
 ('New Zealand', 'Stephens Inc'): RangeIndex(start=85, stop=86, step=1),
 ('Oman', 'Garcia-Jimenez'): RangeIndex(start=83, stop=84, step=1),
 ('Oman', 'Singleton and Sons'): RangeIndex(start=15, stop=16, step=1),
 ('Palau',
  'Price, Sexton and Mcdaniel'): RangeIndex(start=45, stop=46, step=1),
 ('Palestinian Territory',
  'Montes PLC'): RangeIndex(start=55, stop=56, step=1),
 ('Panama', 'Giles Ltd'): RangeIndex(start=25, stop=26, step=1),
 ('Paraguay', 'Greer and Sons'): RangeIndex(start=22, stop=23, step=1),
 ('Poland', 'Anderson Ltd'): RangeIndex(start=39, stop=40, step=1),
 ('Portugal',
  'Brennan, Camacho and Tapia'): RangeIndex(start=60, stop=61, step=1),
 ('Russian Federation', 'Parrish Ltd'): RangeIndex(start=73, stop=74, step=1),
 ('Saint Barthelemy', 'Costa PLC'): RangeIndex(start=56, stop=57, step=1),
 ('Saint Vincent and the Grenadines',
  'Coffey, Lamb and Johnson'): RangeIndex(start=81, stop=82, step=1),
 ('Saint Vincent and the Grenadines',
  'Santana-Duran'): RangeIndex(start=28, stop=29, step=1),
 ('Sao Tome and Principe', 'Petty Ltd'): RangeIndex(start=59, stop=60, step=1),
 ('Singapore', 'Carter-Hancock'): RangeIndex(start=14, stop=15, step=1),
 ('Solomon Islands', 'Glover and Sons'): RangeIndex(start=37, stop=38, step=1),
 ('Solomon Islands', 'Guzman-Brown'): RangeIndex(start=74, stop=75, step=1),
 ('Solomon Islands',
  'Lee, Lucero and Johnson'): RangeIndex(start=93, stop=94, step=1),
 ('South Georgia and the South Sandwich Islands',
  'Moore, Mccoy and Glass'): RangeIndex(start=58, stop=59, step=1),
 ('South Georgia and the South Sandwich Islands',
  'Simon LLC'): RangeIndex(start=18, stop=19, step=1),
 ('Sri Lanka', 'Carpenter-Cook'): RangeIndex(start=13, stop=14, step=1),
 ('Sri Lanka', 'Ware, Burns and Oneal'): RangeIndex(start=96, stop=97, step=1),
 ('Swaziland',
  'Christian, Winters and Ellis'): RangeIndex(start=52, stop=53, step=1),
 ('Switzerland',
  'Hinton, Chaney and Stokes'): RangeIndex(start=27, stop=28, step=1),
 ('Tanzania', 'Sawyer PLC'): RangeIndex(start=29, stop=30, step=1),
 ('Timor-Leste', 'Beck-Hendrix'): RangeIndex(start=9, stop=10, step=1),
 ('Togo', 'Graham-Francis'): RangeIndex(start=12, stop=13, step=1),
 ('Togo', 'Prince, Malone and Pugh'): RangeIndex(start=61, stop=62, step=1),
 ('United Arab Emirates', 'Novak LLC'): RangeIndex(start=57, stop=58, step=1),
 ('United Arab Emirates',
  'Osborne-Erickson'): RangeIndex(start=48, stop=49, step=1),
 ('United States Virgin Islands',
  'Chang, Aguirre and Leblanc'): RangeIndex(start=75, stop=76, step=1),
 ('United States of America',
  'Herrera Group'): RangeIndex(start=33, stop=34, step=1),
 ('Uruguay', 'Jordan Ltd'): RangeIndex(start=36, stop=37, step=1),
 ('Uzbekistan', 'Short-Wiggins'): RangeIndex(start=46, stop=47, step=1),
 ('Vietnam',
  'Hoffman, Reed and Mcclain'): RangeIndex(start=11, stop=12, step=1),
 ('Western Sahara', 'Winters-Mendoza'): RangeIndex(start=16, stop=17, step=1),
 ('Zimbabwe',
  'Acosta, Petersen and Morrow'): RangeIndex(start=30, stop=31, step=1),
 ('Zimbabwe', 'Huynh and Sons'): RangeIndex(start=72, stop=73, step=1)}

In [20]:
for Country, df_1 in gr1:
    print(Country)
    print(df_1)

Acosta, Petersen and Morrow
    Index      Customer Id First Name Last Name                      Company  \
30     31  64DCcDFaB9DFd4e       Jack      Tate  Acosta, Petersen and Morrow

           City   Country             Phone 1            Phone 2  \
30  West Samuel  Zimbabwe  965-108-4406x20714  046.906.1442x6784

                         Email Subscription Date  \
30  gfigueroa@boone-zavala.com        15-09-2021

                           Website
30  http://www.hawkins-ramsey.com/
Adkins-Salinas
    Index      Customer Id First Name Last Name         Company  \
32     33  7Ce381e4Afa4ba9    Gabriel     Mejia  Adkins-Salinas

             City        Country     Phone 1             Phone 2  \
32  Port Annatown  Liechtenstein  4077245425  646.044.0696x66800

                     Email Subscription Date                     Website
32  coleolson@jennings.net        24-04-2021  https://patel-hanson.info/
Anderson Ltd
    Index      Customer Id First Name Last Name       Company       City  \
39     40  17aD8e2dB3df03D     Sherry     Garza  Anderson Ltd  West John

   Country               Phone 1             Phone 2             Email  \
39  Poland  001-067-713-6440x158  (978)289-8785x5766  ann48@miller.com

   Subscription Date             Website
39        01-11-2021  http://spence.com/
Beck-Hendrix
   Index      Customer Id First Name  Last Name       Company        City  \
9     10  8C2811a503C7c5a   Michelle  Gallagher  Beck-Hendrix  Elaineberg

       Country           Phone 1               Phone 2              Email  \
9  Timor-Leste  739.218.2516x459  001-054-401-0347x617  mdyer@escobar.net

  Subscription Date             Website
9        08-11-2021  https://arias.com/
Blankenship-Arias
    Index      Customer Id First Name Last Name            Company       City  \
80     81  D6CEAfb3BDbaa1A     Leslie  Jennings  Blankenship-Arias  Coreybury

       Country       Phone 1       Phone 2                Email  \
80  Micronesia  629.198.6346  075.256.0829  corey75@wiggins.com

   Subscription Date                  Website
80        13-11-2021  https://www.juarez.com/
Brennan, Acosta and Ramos
    Index      Customer Id First Name Last Name                    Company  \
47     48  283DFCD0Dba40aF     Gloria    Mccall  Brennan, Acosta and Ramos

              City Country       Phone 1                Phone 2  \
47  North Kerriton   Ghana  445-603-6729  001-395-959-4736x4524

                            Email Subscription Date                    Website
47  bartlettjenna@zuniga-moss.biz        11-03-2022  http://burgess-frank.com/
Brennan, Camacho and Tapia
    Index      Customer Id First Name Last Name                     Company  \
60     61  a940cE42e035F28       Lynn      Pham  Brennan, Camacho and Tapia

               City   Country           Phone 1           Phone 2  \
60  East Pennyshire  Portugal  846.468.6834x611  001-248-691-0006

                    Email Subscription Date                  Website
60  mpham@rios-guzman.com        21-08-2020  https://www.murphy.com/
Browning-Simon
   Index      Customer Id First Name Last Name         Company          City  \
8      9  C2dE4dEEc489ae0     Sheryl    Meyers  Browning-Simon  East Leonard

  Country            Phone 1              Phone 2                    Email  \
8   Chile  854-138-4911x5772  +1-448-910-2276x729  mariokhan@ryan-pope.org

  Subscription Date                   Website
8        13-01-2020  https://www.bullock.net/
Byrd Inc
    Index      Customer Id First Name Last Name   Company         City  \
53     54  c09952De6Cda8aA     Stacie   Richard  Byrd Inc  New Deborah

       Country                 Phone 1                Phone 2  \
53  Madagascar  001-622-948-3641x24810  001-731-168-2893x8891

                        Email Subscription Date           Website
53  clinton85@colon-arias.org        15-10-2020  https://kim.com/
Byrd-Campbell
    Index      Customer Id First Name Last Name        Company  \
90     91  5ef6d3eefdD43bE       Nina    Chavez  Byrd-Campbell

              City Country       Phone 1              Phone 2  \
90  Cassidychester   Chile  053-344-3205  +1-330-920-5422x571

                   Email Subscription Date                Website
90  elliserica@frank.com        26-03-2020  https://www.pugh.com/
Caldwell Group
    Index      Customer Id First Name Last Name         Company  \
62     63  aEcbe5365BbC67D      Eddie   Jimenez  Caldwell Group

             City   Country               Phone 1             Phone 2  \
62  West Kristine  Ethiopia  +1-235-657-1073x6306  (026)401-7353x2417

                        Email Subscription Date             Website
62  kristiwhitney@bernard.com        24-03-2022  http://cherry.com/
Carey LLC
    Index      Customer Id First Name Last Name    Company          City  \
95     96  cb8E23e48d22Eae       Karl     Greer  Carey LLC  East Leonard

   Country              Phone 1               Phone 2             Email  \
95   Chile  (188)169-1674x58692  001-841-293-3519x614  hhart@jensen.com

   Subscription Date                  Website
95        30-01-2022  http://hayes-perez.com/
Carpenter-Cook
    Index      Customer Id First Name Last Name         Company      City  \
13     14  A08A8aF8BE9FaD4   Kristine       Cox  Carpenter-Cook  Jodyberg

      Country             Phone 1               Phone 2  \
13  Sri Lanka  786-284-3358x62152  +1-315-627-1796x8074

                       Email Subscription Date                  Website
13  holdenmiranda@clarke.com        08-02-2021  https://www.brandt.com/
Carter-Hancock
    Index      Customer Id First Name Last Name         Company       City  \
14     15  6fEaA1b7cab7B6C      Faith      Lutz  Carter-Hancock  Burchbury

      Country             Phone 1       Phone 2  \
14  Singapore  (781)861-7180x8306  207-185-3665

                                Email Subscription Date                Website
14  cassieparrish@blevins-chapman.net        26-01-2022  http://stevenson.org/
Carter-Strickland
    Index      Customer Id First Name Last Name            Company  \
88     89  efeb73245CDf1fF     Vernon      Kane  Carter-Strickland

          City Country           Phone 1       Phone 2  \
88  Thomasfurt   Chile  114-854-1159x555  499-608-4612

                     Email Subscription Date                        Website
88  hilljesse@barrett.info        15-04-2021  http://www.duffy-hensley.net/
Chang, Aguirre and Leblanc
    Index      Customer Id First Name Last Name                     Company  \
75     76  d40e89dCade7b2F      Debra    Riddle  Chang, Aguirre and Leblanc

          City                       Country                Phone 1  \
75  Colinhaven  United States Virgin Islands  +1-768-182-6014x14336

          Phone 2                    Email Subscription Date  \
75  (303)961-4491  shieldskerry@robles.com        11-07-2020

                Website
75  http://kaiser.info/
Christian, Winters and Ellis
    Index      Customer Id First Name Last Name                       Company  \
52     53  faCEF517ae7D8eB   Patricia   Goodwin  Christian, Winters and Ellis

         City    Country             Phone 1        Phone 2  \
52  Cowanfort  Swaziland  322.549.7139x70040  (111)741-4173

                      Email Subscription Date             Website
52  vaughanchristy@lara.biz        08-03-2021  http://clark.info/
Church-Banks
    Index      Customer Id First Name Last Name       Company        City  \
65     66  fF1b6c9E8Fbf1ff   Fernando   Lambert  Church-Banks  Lake Nancy

      Country       Phone 1     Phone 2                     Email  \
65  Lithuania  497.829.9038  3863743398  fisherlinda@schaefer.net

   Subscription Date                Website
65        23-04-2021  https://www.vang.com/
Coffey, Lamb and Johnson
    Index      Customer Id First Name Last Name                   Company  \
81     82  Ebdb6F6F7c90b69   Kathleen     Mckay  Coffey, Lamb and Johnson

              City                           Country        Phone 1  \
81  Lake Janiceton  Saint Vincent and the Grenadines  (733)910-9968

               Phone 2                              Email Subscription Date  \
81  (691)247-4128x0665  chloelester@higgins-wilkinson.com        12-09-2021

                         Website
81  http://www.owens-mooney.com/
Combs, Waller and Durham
    Index      Customer Id First Name Last Name                   Company  \
79     80  A7F85c1DE4dB87f  Alejandro     Blair  Combs, Waller and Durham

          City  Country              Phone 1            Phone 2  \
79  Thomasland  Iceland  (690)068-4641x51468  555.509.8691x2329

                      Email Subscription Date                       Website
79  elizabethbarr@ewing.com        19-09-2020  https://mercado-blevins.com/
Conway-Mcbride
    Index      Customer Id First Name Last Name         Company  \
71     72  Ef859092FbEcC07    Richard      Roth  Conway-Mcbride

                City  Country       Phone 1     Phone 2  \
71  New Jasmineshire  Morocco  581-440-6539  9857827463

                          Email Subscription Date                  Website
71  aharper@maddox-townsend.org        23-02-2020  https://www.brooks.com/
Costa PLC
    Index      Customer Id First Name  Last Name    Company          City  \
56     57  c8FE57cBBdCDcb2    Phyllis  Maldonado  Costa PLC  Lake Whitney

             Country     Phone 1               Phone 2  \
56  Saint Barthelemy  4500370767  001-508-064-6725x017

                      Email Subscription Date                  Website
56  yhanson@warner-diaz.org        25-01-2021  http://www.bernard.com/
Cross PLC
    Index      Customer Id First Name Last Name    Company        City  \
43     44  D3fC11A9C235Dc6       Luis     Greer  Cross PLC  North Drew

     Country               Phone 1            Phone 2  \
43  Bulgaria  001-336-025-6849x701  684.698.2911x6092

                             Email Subscription Date  \
43  bstuart@williamson-mcclure.com        15-05-2022

                          Website
43  https://fletcher-nielsen.com/
Decker-Mcknight
    Index      Customer Id First Name Last Name          Company  \
89     90  37Ec4B395641c1E       Lori   Flowers  Decker-Mcknight

              City  Country       Phone 1            Phone 2  \
89  North Joeburgh  Namibia  679.415.1210  945-842-3659x4581

                       Email Subscription Date                        Website
89  tyrone77@valenzuela.info        09-01-2021  http://www.deleon-crosby.com/
Dominguez, Mcmillan and Donovan
   Index      Customer Id First Name Last Name  \
3      4  5Cef8BFA16c5e3c      Linda     Olsen

                           Company          City Country  \
3  Dominguez, Mcmillan and Donovan  East Leonard   Chile

                  Phone 1 Phone 2                        Email  \
3  001-808-617-6467x12895   -9892  stanleyblackwell@benson.org

  Subscription Date                     Website
3        02-06-2020  http://www.good-lyons.com/
Donaldson-Dougherty
    Index      Customer Id First Name Last Name              Company  \
67     68  a014Ec1b9FccC1E        Tom  Alvarado  Donaldson-Dougherty

                City   Country             Phone 1            Phone 2  \
67  South Sophiaberg  Kiribati  (585)606-2980x2258  730-797-3594x5614

                            Email Subscription Date                  Website
67  nicholsonnina@montgomery.info        18-08-2020  http://odom-massey.com/
Fitzgerald-Harrell
    Index      Customer Id First Name Last Name             Company  \
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer  Fitzgerald-Harrell

            City Country        Phone 1                 Phone 2  \
98  East Leonard   Chile  (530)311-9786  001-869-452-0943x12424

                             Email Subscription Date               Website
98  mccarthystephen@horn-green.biz        11-08-2021  http://watkins.info/
Fitzpatrick-Lawrence
    Index      Customer Id First Name Last Name               Company  \
82     83  E8E7e8Cfe516ef0     Hunter    Moreno  Fitzpatrick-Lawrence

            City      Country        Phone 1           Phone 2  \
82  East Clinton  Isle of Man  (733)833-6754  001-761-013-7121

                        Email Subscription Date             Website
82  isaac26@benton-finley.com        28-12-2020  http://walls.info/
Garcia-Jimenez
    Index      Customer Id First Name Last Name         Company  \
83     84  78C06E9b6B3DF20       Chad  Davidson  Garcia-Jimenez

                 City Country     Phone 1        Phone 2  \
83  South Joshuashire    Oman  8275702958  (804)842-4715

                        Email Subscription Date                        Website
83  justinwalters@jimenez.com        15-11-2021  http://www.garner-oliver.com/
Giles Ltd
    Index      Customer Id First Name Last Name    Company         City  \
25     26  09D7D7C8Fe09aea     Marcus     Moody  Giles Ltd  Kaitlyntown

   Country       Phone 1           Phone 2                            Email  \
25  Panama  674-677-8623  909-277-5485x566  donnamullins@norris-barrett.org

   Subscription Date                 Website
25        24-05-2022  https://www.curry.com/
Glover and Sons
    Index      Customer Id First Name Last Name          Company  \
37     38  7a1Ee69F4fF4B4D     Jordan       Gay  Glover and Sons

            City          Country     Phone 1     Phone 2  \
37  South Walter  Solomon Islands  7208417020  8035336772

                                 Email Subscription Date              Website
37  tiffanydavies@harris-mcfarland.org        24-02-2021  http://www.lee.org/
Graham-Francis
    Index      Customer Id First Name Last Name         Company  \
12     13  e35426EbDEceaFF     Tracey      Mata  Graham-Francis

                 City Country           Phone 1        Phone 2  \
12  South Joannamouth    Togo  001-949-844-8787  (855)713-8773

               Email Subscription Date               Website
12  alex56@walls.org        02-12-2021  http://www.beck.com/
Greer and Sons
    Index      Customer Id First Name Last Name         Company          City  \
22     23  2FB0FAA1d429421    Colleen    Howard  Greer and Sons  Brittanyview

     Country     Phone 1             Phone 2                       Email  \
22  Paraguay  1935085151  (947)115-7711x5488  rsingleton@ryan-cherry.com

   Subscription Date           Website
22        19-08-2020  http://paul.biz/
Guzman-Brown
    Index      Customer Id First Name Last Name       Company     City  \
74     75  D01Af0AF7cBbFeA     Regina     Stein  Guzman-Brown  Raystad

            Country                Phone 1                 Phone 2  \
74  Solomon Islands  001-469-848-0724x4407  001-085-360-4426x00357

                        Email Subscription Date                    Website
74  zrosario@rojas-hardin.net        15-01-2022  http://www.johnston.info/
Henderson Inc
    Index      Customer Id First Name Last Name        Company        City  \
66     67  2A13F74EAa7DA6c    Makayla    Cannon  Henderson Inc  Georgeport

          Country                 Phone 1       Phone 2  \
66  New Caledonia  001-215-801-6392x46009  027-609-6460

                     Email Subscription Date                    Website
66  scottcurtis@hurley.biz        20-01-2020  http://www.velazquez.net/
Herrera Group
    Index      Customer Id First Name Last Name        Company         City  \
33     34  A09AEc6E3bF70eE    Kaitlyn   Santana  Herrera Group  New Kaitlyn

                     Country     Phone 1             Phone 2  \
33  United States of America  6303643286  447-710-6202x07313

                   Email Subscription Date           Website
33  georgeross@miles.org        21-09-2021  http://pham.com/
Herrera, Shepherd and Underwood
    Index      Customer Id First Name Last Name  \
44     45  30Dfa48fe5Ede78     Rhonda     Frost

                            Company             City Country        Phone 1  \
44  Herrera, Shepherd and Underwood  Lake Lindaburgh  Monaco  (127)081-9339

                 Phone 2                     Email Subscription Date  \
44  +1-431-028-3337x3492  zkrueger@wolf-chavez.net        06-12-2021

                 Website
44  http://www.khan.com/
Hinton, Chaney and Stokes
    Index      Customer Id First Name Last Name                    Company  \
27     28  b92EBfdF8a3f0E6  Frederick    Harper  Hinton, Chaney and Stokes

                 City      Country               Phone 1       Phone 2  \
27  South Marissatown  Switzerland  +1-077-121-1558x0687  264.742.7149

                   Email Subscription Date                Website
27  jacobkhan@bright.biz        26-05-2022  https://callahan.org/
Hobbs, Garrett and Sanford
    Index      Customer Id First Name Last Name                     Company  \
49     50  80F33Fd2AcebF05     Latoya    Mccann  Hobbs, Garrett and Sanford

               City  Country              Phone 1             Phone 2  \
49  Port Sergiofort  Belarus  (530)287-4548x29481  162-234-0249x32790

                   Email Subscription Date                  Website
49  bobhammond@barry.biz        02-12-2021  https://www.burton.com/
Hoffman, Reed and Mcclain
    Index      Customer Id First Name Last Name                    Company  \
11     12  CEDec94deE6d69B      Jenna    Dodson  Hoffman, Reed and Mcclain

           City  Country        Phone 1                Phone 2  \
11  East Andrea  Vietnam  (041)737-3846  +1-556-888-3485x42608

                 Email Subscription Date                  Website
11  mark42@robbins.com        29-11-2020  http://www.douglas.net/
Huerta-Mclean
    Index      Customer Id First Name Last Name        Company       City  \
38     39  dca4f1D0A0fc5c9      Bruce   Esparza  Huerta-Mclean  Poolefurt

       Country       Phone 1                Phone 2                 Email  \
38  Montenegro  559-529-4424  001-625-000-7132x0367  preese@frye-vega.com

   Subscription Date                 Website
38        22-10-2021  http://www.farley.org/
Huynh and Sons
    Index      Customer Id First Name Last Name         Company  \
72     73  F560f2d3cDFb618    Candice    Keller  Huynh and Sons

               City   Country                 Phone 1                 Phone 2  \
72  East Summerstad  Zimbabwe  001-927-965-8550x92406  001-243-038-4271x53076

                       Email Subscription Date                  Website
72  buckleycory@odonnell.net        22-08-2020  https://www.lucero.com/
Jordan Ltd
    Index      Customer Id First Name Last Name     Company          City  \
36     37  889eCf90f68c5Da   Nicholas      Sosa  Jordan Ltd  South Hunter

    Country        Phone 1       Phone 2              Email Subscription Date  \
36  Uruguay  (661)425-6042  975-998-1519  fwolfe@dorsey.com        10-08-2021

                              Website
36  https://www.fleming-richards.com/
Kaufman and Sons
    Index      Customer Id First Name Last Name           Company  \
41     42  6e5ad5a5e2bB5Ca      Bryan      Dunn  Kaufman and Sons

             City       Country           Phone 1             Phone 2  \
41  North Jimstad  Burkina Faso  001-710-802-5565  078.699.8982x13881

                        Email Subscription Date                 Website
41  woodwardandres@phelps.com        08-09-2021  http://www.butler.com/
Keller-Coffey
    Index      Customer Id  First Name Last Name        Company         City  \
70     71  CBCd2Ac8E3eBDF9  Alexandria      Buck  Keller-Coffey  Nicolasfort

   Country             Phone 1             Phone 2              Email  \
70    Iran  078-900-4760x76668  414-112-8700x68751  lee48@manning.com

   Subscription Date              Website
70        20-02-2021  https://ramsey.org/
Knight, Abbott and Hubbard
    Index      Customer Id First Name Last Name                     Company  \
64     65  636cBF0835E10ff     Eileen     Lynch  Knight, Abbott and Hubbard

            City  Country                Phone 1               Phone 2  \
64  Helenborough  Liberia  +1-158-951-4131x53578  001-673-779-6713x680

                    Email Subscription Date            Website
64  levigiles@vincent.com        02-01-2021  http://mckay.com/
Lamb-Peterson

In [21]:
list(gr1)

[('Acosta, Petersen and Morrow',
      Index      Customer Id First Name Last Name                      Company  \
  30     31  64DCcDFaB9DFd4e       Jack      Tate  Acosta, Petersen and Morrow

             City   Country             Phone 1            Phone 2  \
  30  West Samuel  Zimbabwe  965-108-4406x20714  046.906.1442x6784

                           Email Subscription Date  \
  30  gfigueroa@boone-zavala.com        15-09-2021

                             Website
  30  http://www.hawkins-ramsey.com/  ),
 ('Adkins-Salinas',
      Index      Customer Id First Name Last Name         Company  \
  32     33  7Ce381e4Afa4ba9    Gabriel     Mejia  Adkins-Salinas

               City        Country     Phone 1             Phone 2  \
  32  Port Annatown  Liechtenstein  4077245425  646.044.0696x66800

                       Email Subscription Date                     Website
  32  coleolson@jennings.net        24-04-2021  https://patel-hanson.info/  ),
 ('Anderson Ltd',
      Index      Customer Id First Name Last Name       Company       City  \
  39     40  17aD8e2dB3df03D     Sherry     Garza  Anderson Ltd  West John

     Country               Phone 1             Phone 2             Email  \
  39  Poland  001-067-713-6440x158  (978)289-8785x5766  ann48@miller.com

     Subscription Date             Website
  39        01-11-2021  http://spence.com/  ),
 ('Beck-Hendrix',
     Index      Customer Id First Name  Last Name       Company        City  \
  9     10  8C2811a503C7c5a   Michelle  Gallagher  Beck-Hendrix  Elaineberg

         Country           Phone 1               Phone 2              Email  \
  9  Timor-Leste  739.218.2516x459  001-054-401-0347x617  mdyer@escobar.net

    Subscription Date             Website
  9        08-11-2021  https://arias.com/  ),
 ('Blankenship-Arias',
      Index      Customer Id First Name Last Name            Company       City  \
  80     81  D6CEAfb3BDbaa1A     Leslie  Jennings  Blankenship-Arias  Coreybury

         Country       Phone 1       Phone 2                Email  \
  80  Micronesia  629.198.6346  075.256.0829  corey75@wiggins.com

     Subscription Date                  Website
  80        13-11-2021  https://www.juarez.com/  ),
 ('Brennan, Acosta and Ramos',
      Index      Customer Id First Name Last Name                    Company  \
  47     48  283DFCD0Dba40aF     Gloria    Mccall  Brennan, Acosta and Ramos

                City Country       Phone 1                Phone 2  \
  47  North Kerriton   Ghana  445-603-6729  001-395-959-4736x4524

                              Email Subscription Date                    Website
  47  bartlettjenna@zuniga-moss.biz        11-03-2022  http://burgess-frank.com/  ),
 ('Brennan, Camacho and Tapia',
      Index      Customer Id First Name Last Name                     Company  \
  60     61  a940cE42e035F28       Lynn      Pham  Brennan, Camacho and Tapia

                 City   Country           Phone 1           Phone 2  \
  60  East Pennyshire  Portugal  846.468.6834x611  001-248-691-0006

                      Email Subscription Date                  Website
  60  mpham@rios-guzman.com        21-08-2020  https://www.murphy.com/  ),
 ('Browning-Simon',
     Index      Customer Id First Name Last Name         Company          City  \
  8      9  C2dE4dEEc489ae0     Sheryl    Meyers  Browning-Simon  East Leonard

    Country            Phone 1              Phone 2                    Email  \
  8   Chile  854-138-4911x5772  +1-448-910-2276x729  mariokhan@ryan-pope.org

    Subscription Date                   Website
  8        13-01-2020  https://www.bullock.net/  ),
 ('Byrd Inc',
      Index      Customer Id First Name Last Name   Company         City  \
  53     54  c09952De6Cda8aA     Stacie   Richard  Byrd Inc  New Deborah

         Country                 Phone 1                Phone 2  \
  53  Madagascar  001-622-948-3641x24810  001-731-168-2893x8891

                          Email Subscription Date           Website
  53  clinton85@colon-arias.org        15-10-2020  https://kim.com/  ),
 ('Byrd-Campbell',
      Index      Customer Id First Name Last Name        Company  \
  90     91  5ef6d3eefdD43bE       Nina    Chavez  Byrd-Campbell

                City Country       Phone 1              Phone 2  \
  90  Cassidychester   Chile  053-344-3205  +1-330-920-5422x571

                     Email Subscription Date                Website
  90  elliserica@frank.com        26-03-2020  https://www.pugh.com/  ),
 ('Caldwell Group',
      Index      Customer Id First Name Last Name         Company  \
  62     63  aEcbe5365BbC67D      Eddie   Jimenez  Caldwell Group

               City   Country               Phone 1             Phone 2  \
  62  West Kristine  Ethiopia  +1-235-657-1073x6306  (026)401-7353x2417

                          Email Subscription Date             Website
  62  kristiwhitney@bernard.com        24-03-2022  http://cherry.com/  ),
 ('Carey LLC',
      Index      Customer Id First Name Last Name    Company          City  \
  95     96  cb8E23e48d22Eae       Karl     Greer  Carey LLC  East Leonard

     Country              Phone 1               Phone 2             Email  \
  95   Chile  (188)169-1674x58692  001-841-293-3519x614  hhart@jensen.com

     Subscription Date                  Website
  95        30-01-2022  http://hayes-perez.com/  ),
 ('Carpenter-Cook',
      Index      Customer Id First Name Last Name         Company      City  \
  13     14  A08A8aF8BE9FaD4   Kristine       Cox  Carpenter-Cook  Jodyberg

        Country             Phone 1               Phone 2  \
  13  Sri Lanka  786-284-3358x62152  +1-315-627-1796x8074

                         Email Subscription Date                  Website
  13  holdenmiranda@clarke.com        08-02-2021  https://www.brandt.com/  ),
 ('Carter-Hancock',
      Index      Customer Id First Name Last Name         Company       City  \
  14     15  6fEaA1b7cab7B6C      Faith      Lutz  Carter-Hancock  Burchbury

        Country             Phone 1       Phone 2  \
  14  Singapore  (781)861-7180x8306  207-185-3665

                                  Email Subscription Date                Website
  14  cassieparrish@blevins-chapman.net        26-01-2022  http://stevenson.org/  ),
 ('Carter-Strickland',
      Index      Customer Id First Name Last Name            Company  \
  88     89  efeb73245CDf1fF     Vernon      Kane  Carter-Strickland

            City Country           Phone 1       Phone 2  \
  88  Thomasfurt   Chile  114-854-1159x555  499-608-4612

                       Email Subscription Date                        Website
  88  hilljesse@barrett.info        15-04-2021  http://www.duffy-hensley.net/  ),
 ('Chang, Aguirre and Leblanc',
      Index      Customer Id First Name Last Name                     Company  \
  75     76  d40e89dCade7b2F      Debra    Riddle  Chang, Aguirre and Leblanc

            City                       Country                Phone 1  \
  75  Colinhaven  United States Virgin Islands  +1-768-182-6014x14336

            Phone 2                    Email Subscription Date  \
  75  (303)961-4491  shieldskerry@robles.com        11-07-2020

                  Website
  75  http://kaiser.info/  ),
 ('Christian, Winters and Ellis',
      Index      Customer Id First Name Last Name                       Company  \
  52     53  faCEF517ae7D8eB   Patricia   Goodwin  Christian, Winters and Ellis

           City    Country             Phone 1        Phone 2  \
  52  Cowanfort  Swaziland  322.549.7139x70040  (111)741-4173

                        Email Subscription Date             Website
  52  vaughanchristy@lara.biz        08-03-2021  http://clark.info/  ),
 ('Church-Banks',
      Index      Customer Id First Name Last Name       Company        City  \
  65     66  fF1b6c9E8Fbf1ff   Fernando   Lambert  Church-Banks  Lake Nancy

        Country       Phone 1     Phone 2                     Email  \
  65  Lithuania  497.829.9038  3863743398  fisherlinda@schaefer.net

     Subscription Date                Website
  65        23-04-2021  https://www.vang.com/  ),
 ('Coffey, Lamb and Johnson',
      Index      Customer Id First Name Last Name                   Company  \
  81     82  Ebdb6F6F7c90b69   Kathleen     Mckay  Coffey, Lamb and Johnson

                City                           Country        Phone 1  \
  81  Lake Janiceton  Saint Vincent and the Grenadines  (733)910-9968

                 Phone 2                              Email Subscription Date  \
  81  (691)247-4128x0665  chloelester@higgins-wilkinson.com        12-09-2021

                           Website
  81  http://www.owens-mooney.com/  ),
 ('Combs, Waller and Durham',
      Index      Customer Id First Name Last Name                   Company  \
  79     80  A7F85c1DE4dB87f  Alejandro     Blair  Combs, Waller and Durham

            City  Country              Phone 1            Phone 2  \
  79  Thomasland  Iceland  (690)068-4641x51468  555.509.8691x2329

                        Email Subscription Date                       Website
  79  elizabethbarr@ewing.com        19-09-2020  https://mercado-blevins.com/  ),
 ('Conway-Mcbride',
      Index      Customer Id First Name Last Name         Company  \
  71     72  Ef859092FbEcC07    Richard      Roth  Conway-Mcbride

                  City  Country       Phone 1     Phone 2  \
  71  New Jasmineshire  Morocco  581-440-6539  9857827463

                            Email Subscription Date                  Website
  71  aharper@maddox-townsend.org        23-02-2020  https://www.brooks.com/  ),
 ('Costa PLC',
      Index      Customer Id First Name  Last Name    Company          City  \
  56     57  c8FE57cBBdCDcb2    Phyllis  Maldonado  Costa PLC  Lake Whitney

               Country     Phone 1               Phone 2  \
  56  Saint Barthelemy  4500370767  001-508-064-6725x017

                        Email Subscription Date                  Website
  56  yhanson@warner-diaz.org        25-01-2021  http://www.bernard.com/  ),
 ('Cross PLC',
      Index      Customer Id First Name Last Name    Company        City  \
  43     44  D3fC11A9C235Dc6       Luis     Greer  Cross PLC  North Drew

       Country               Phone 1            Phone 2  \
  43  Bulgaria  001-336-025-6849x701  684.698.2911x6092

                               Email Subscription Date  \
  43  bstuart@williamson-mcclure.com        15-05-2022

                            Website
  43  https://fletcher-nielsen.com/  ),
 ('Decker-Mcknight',
      Index      Customer Id First Name Last Name          Company  \
  89     90  37Ec4B395641c1E       Lori   Flowers  Decker-Mcknight

                City  Country       Phone 1            Phone 2  \
  89  North Joeburgh  Namibia  679.415.1210  945-842-3659x4581

                         Email Subscription Date                        Website
  89  tyrone77@valenzuela.info        09-01-2021  http://www.deleon-crosby.com/  ),
 ('Dominguez, Mcmillan and Donovan',
     Index      Customer Id First Name Last Name  \
  3      4  5Cef8BFA16c5e3c      Linda     Olsen

                             Company          City Country  \
  3  Dominguez, Mcmillan and Donovan  East Leonard   Chile

                    Phone 1 Phone 2                        Email  \
  3  001-808-617-6467x12895   -9892  stanleyblackwell@benson.org

    Subscription Date                     Website
  3        02-06-2020  http://www.good-lyons.com/  ),
 ('Donaldson-Dougherty',
      Index      Customer Id First Name Last Name              Company  \
  67     68  a014Ec1b9FccC1E        Tom  Alvarado  Donaldson-Dougherty

                  City   Country             Phone 1            Phone 2  \
  67  South Sophiaberg  Kiribati  (585)606-2980x2258  730-797-3594x5614

                              Email Subscription Date                  Website
  67  nicholsonnina@montgomery.info        18-08-2020  http://odom-massey.com/  ),
 ('Fitzgerald-Harrell',
      Index      Customer Id First Name Last Name             Company  \
  98     99  c23d1D9EE8DEB0A     Yvonne    Farmer  Fitzgerald-Harrell

              City Country        Phone 1                 Phone 2  \
  98  East Leonard   Chile  (530)311-9786  001-869-452-0943x12424

                               Email Subscription Date               Website
  98  mccarthystephen@horn-green.biz        11-08-2021  http://watkins.info/  ),
 ('Fitzpatrick-Lawrence',
      Index      Customer Id First Name Last Name               Company  \
  82     83  E8E7e8Cfe516ef0     Hunter    Moreno  Fitzpatrick-Lawrence

              City      Country        Phone 1           Phone 2  \
  82  East Clinton  Isle of Man  (733)833-6754  001-761-013-7121

                          Email Subscription Date             Website
  82  isaac26@benton-finley.com        28-12-2020  http://walls.info/  ),
 ('Garcia-Jimenez',
      Index      Customer Id First Name Last Name         Company  \
  83     84  78C06E9b6B3DF20       Chad  Davidson  Garcia-Jimenez

                   City Country     Phone 1        Phone 2  \
  83  South Joshuashire    Oman  8275702958  (804)842-4715

                          Email Subscription Date                        Website
  83  justinwalters@jimenez.com        15-11-2021  http://www.garner-oliver.com/  ),
 ('Giles Ltd',
      Index      Customer Id First Name Last Name    Company         City  \
  25     26  09D7D7C8Fe09aea     Marcus     Moody  Giles Ltd  Kaitlyntown

     Country       Phone 1           Phone 2                            Email  \
  25  Panama  674-677-8623  909-277-5485x566  donnamullins@norris-barrett.org

     Subscription Date                 Website
  25        24-05-2022  https://www.curry.com/  ),
 ('Glover and Sons',
      Index      Customer Id First Name Last Name          Company  \
  37     38  7a1Ee69F4fF4B4D     Jordan       Gay  Glover and Sons

              City          Country     Phone 1     Phone 2  \
  37  South Walter  Solomon Islands  7208417020  8035336772

                                   Email Subscription Date              Website
  37  tiffanydavies@harris-mcfarland.org        24-02-2021  http://www.lee.org/  ),
 ('Graham-Francis',
      Index      Customer Id First Name Last Name         Company  \
  12     13  e35426EbDEceaFF     Tracey      Mata  Graham-Francis

                   City Country           Phone 1        Phone 2  \
  12  South Joannamouth    Togo  001-949-844-8787  (855)713-8773

                 Email Subscription Date               Website
  12  alex56@walls.org        02-12-2021  http://www.beck.com/  ),
 ('Greer and Sons',
      Index      Customer Id First Name Last Name         Company          City  \
  22     23  2FB0FAA1d429421    Colleen    Howard  Greer and Sons  Brittanyview

       Country     Phone 1             Phone 2                       Email  \
  22  Paraguay  1935085151  (947)115-7711x5488  rsingleton@ryan-cherry.com

     Subscription Date           Website
  22        19-08-2020  http://paul.biz/  ),
 ('Guzman-Brown',
      Index      Customer Id First Name Last Name       Company     City  \
  74     75  D01Af0AF7cBbFeA     Regina     Stein  Guzman-Brown  Raystad

              Country                Phone 1                 Phone 2  \
  74  Solomon Islands  001-469-848-0724x4407  001-085-360-4426x00357

                          Email Subscription Date                    Website
  74  zrosario@rojas-hardin.net        15-01-2022  http://www.johnston.info/  ),
 ('Henderson Inc',
      Index      Customer Id First Name Last Name        Company        City  \
  66     67  2A13F74EAa7DA6c    Makayla    Cannon  Henderson Inc  Georgeport

            Country                 Phone 1       Phone 2  \
  66  New Caledonia  001-215-801-6392x46009  027-609-6460

                       Email Subscription Date                    Website
  66  scottcurtis@hurley.biz        20-01-2020  http://www.velazquez.net/  ),
 ('Herrera Group',
      Index      Customer Id First Name Last Name        Company         City  \
  33     34  A09AEc6E3bF70eE    Kaitlyn   Santana  Herrera Group  New Kaitlyn

                       Country     Phone 1             Phone 2  \
  33  United States of America  6303643286  447-710-6202x07313

                     Email Subscription Date           Website
  33  georgeross@miles.org        21-09-2021  http://pham.com/  ),
 ('Herrera, Shepherd and Underwood',
      Index      Customer Id First Name Last Name  \
  44     45  30Dfa48fe5Ede78     Rhonda     Frost

                              Company             City Country        Phone 1  \
  44  Herrera, Shepherd and Underwood  Lake Lindaburgh  Monaco  (127)081-9339

                   Phone 2                     Email Subscription Date  \
  44  +1-431-028-3337x3492  zkrueger@wolf-chavez.net        06-12-2021

                   Website
  44  http://www.khan.com/  ),
 ('Hinton, Chaney and Stokes',
      Index      Customer Id First Name Last Name                    Company  \
  27     28  b92EBfdF8a3f0E6  Frederick    Harper  Hinton, Chaney and Stokes

                   City      Country               Phone 1       Phone 2  \
  27  South Marissatown  Switzerland  +1-077-121-1558x0687  264.742.7149

                     Email Subscription Date                Website
  27  jacobkhan@bright.biz        26-05-2022  https://callahan.org/  ),
 ('Hobbs, Garrett and Sanford',
      Index      Customer Id First Name Last Name                     Company  \
  49     50  80F33Fd2AcebF05     Latoya    Mccann  Hobbs, Garrett and Sanford

                 City  Country              Phone 1             Phone 2  \
  49  Port Sergiofort  Belarus  (530)287-4548x29481  162-234-0249x32790

                     Email Subscription Date                  Website
  49  bobhammond@barry.biz        02-12-2021  https://www.burton.com/  ),
 ('Hoffman, Reed and Mcclain',
      Index      Customer Id First Name Last Name                    Company  \
  11     12  CEDec94deE6d69B      Jenna    Dodson  Hoffman, Reed and Mcclain

             City  Country        Phone 1                Phone 2  \
  11  East Andrea  Vietnam  (041)737-3846  +1-556-888-3485x42608

                   Email Subscription Date                  Website
  11  mark42@robbins.com        29-11-2020  http://www.douglas.net/  ),
 ('Huerta-Mclean',
      Index      Customer Id First Name Last Name        Company       City  \
  38     39  dca4f1D0A0fc5c9      Bruce   Esparza  Huerta-Mclean  Poolefurt

         Country       Phone 1                Phone 2                 Email  \
  38  Montenegro  559-529-4424  001-625-000-7132x0367  preese@frye-vega.com

     Subscription Date                 Website
  38        22-10-2021  http://www.farley.org/  ),
 ('Huynh and Sons',
      Index      Customer Id First Name Last Name         Company  \
  72     73  F560f2d3cDFb618    Candice    Keller  Huynh and Sons

                 City   Country                 Phone 1                 Phone 2  \
  72  East Summerstad  Zimbabwe  001-927-965-8550x92406  001-243-038-4271x53076

                         Email Subscription Date                  Website
  72  buckleycory@odonnell.net        22-08-2020  https://www.lucero.com/  ),
 ('Jordan Ltd',
      Index      Customer Id First Name Last Name     Company          City  \
  36     37  889eCf90f68c5Da   Nicholas      Sosa  Jordan Ltd  South Hunter

      Country        Phone 1       Phone 2              Email Subscription Date  \
  36  Uruguay  (661)425-6042  975-998-1519  fwolfe@dorsey.com        10-08-2021

                                Website
  36  https://www.fleming-richards.com/  ),
 ('Kaufman and Sons',
      Index      Customer Id First Name Last Name           Company  \
  41     42  6e5ad5a5e2bB5Ca      Bryan      Dunn  Kaufman and Sons

               City       Country           Phone 1             Phone 2  \
  41  North Jimstad  Burkina Faso  001-710-802-5565  078.699.8982x13881

                          Email Subscription Date                 Website

In [22]:
dict(list(gr1))

{'Acosta, Petersen and Morrow':     Index      Customer Id First Name Last Name                      Company  \
 30     31  64DCcDFaB9DFd4e       Jack      Tate  Acosta, Petersen and Morrow

            City   Country             Phone 1            Phone 2  \
 30  West Samuel  Zimbabwe  965-108-4406x20714  046.906.1442x6784

                          Email Subscription Date  \
 30  gfigueroa@boone-zavala.com        15-09-2021

                            Website
 30  http://www.hawkins-ramsey.com/  ,
 'Adkins-Salinas':     Index      Customer Id First Name Last Name         Company  \
 32     33  7Ce381e4Afa4ba9    Gabriel     Mejia  Adkins-Salinas

              City        Country     Phone 1             Phone 2  \
 32  Port Annatown  Liechtenstein  4077245425  646.044.0696x66800

                      Email Subscription Date                     Website
 32  coleolson@jennings.net        24-04-2021  https://patel-hanson.info/  ,
 'Anderson Ltd':     Index      Customer Id First Name Last Name       Company       City  \
 39     40  17aD8e2dB3df03D     Sherry     Garza  Anderson Ltd  West John

    Country               Phone 1             Phone 2             Email  \
 39  Poland  001-067-713-6440x158  (978)289-8785x5766  ann48@miller.com

    Subscription Date             Website
 39        01-11-2021  http://spence.com/  ,
 'Beck-Hendrix':    Index      Customer Id First Name  Last Name       Company        City  \
 9     10  8C2811a503C7c5a   Michelle  Gallagher  Beck-Hendrix  Elaineberg

        Country           Phone 1               Phone 2              Email  \
 9  Timor-Leste  739.218.2516x459  001-054-401-0347x617  mdyer@escobar.net

   Subscription Date             Website
 9        08-11-2021  https://arias.com/  ,
 'Blankenship-Arias':     Index      Customer Id First Name Last Name            Company       City  \
 80     81  D6CEAfb3BDbaa1A     Leslie  Jennings  Blankenship-Arias  Coreybury

        Country       Phone 1       Phone 2                Email  \
 80  Micronesia  629.198.6346  075.256.0829  corey75@wiggins.com

    Subscription Date                  Website
 80        13-11-2021  https://www.juarez.com/  ,
 'Brennan, Acosta and Ramos':     Index      Customer Id First Name Last Name                    Company  \
 47     48  283DFCD0Dba40aF     Gloria    Mccall  Brennan, Acosta and Ramos

               City Country       Phone 1                Phone 2  \
 47  North Kerriton   Ghana  445-603-6729  001-395-959-4736x4524

                             Email Subscription Date                    Website
 47  bartlettjenna@zuniga-moss.biz        11-03-2022  http://burgess-frank.com/  ,
 'Brennan, Camacho and Tapia':     Index      Customer Id First Name Last Name                     Company  \
 60     61  a940cE42e035F28       Lynn      Pham  Brennan, Camacho and Tapia

                City   Country           Phone 1           Phone 2  \
 60  East Pennyshire  Portugal  846.468.6834x611  001-248-691-0006

                     Email Subscription Date                  Website
 60  mpham@rios-guzman.com        21-08-2020  https://www.murphy.com/  ,
 'Browning-Simon':    Index      Customer Id First Name Last Name         Company          City  \
 8      9  C2dE4dEEc489ae0     Sheryl    Meyers  Browning-Simon  East Leonard

   Country            Phone 1              Phone 2                    Email  \
 8   Chile  854-138-4911x5772  +1-448-910-2276x729  mariokhan@ryan-pope.org

   Subscription Date                   Website
 8        13-01-2020  https://www.bullock.net/  ,
 'Byrd Inc':     Index      Customer Id First Name Last Name   Company         City  \
 53     54  c09952De6Cda8aA     Stacie   Richard  Byrd Inc  New Deborah

        Country                 Phone 1                Phone 2  \
 53  Madagascar  001-622-948-3641x24810  001-731-168-2893x8891

                         Email Subscription Date           Website
 53  clinton85@colon-arias.org        15-10-2020  https://kim.com/  ,
 'Byrd-Campbell':     Index      Customer Id First Name Last Name        Company  \
 90     91  5ef6d3eefdD43bE       Nina    Chavez  Byrd-Campbell

               City Country       Phone 1              Phone 2  \
 90  Cassidychester   Chile  053-344-3205  +1-330-920-5422x571

                    Email Subscription Date                Website
 90  elliserica@frank.com        26-03-2020  https://www.pugh.com/  ,
 'Caldwell Group':     Index      Customer Id First Name Last Name         Company  \
 62     63  aEcbe5365BbC67D      Eddie   Jimenez  Caldwell Group

              City   Country               Phone 1             Phone 2  \
 62  West Kristine  Ethiopia  +1-235-657-1073x6306  (026)401-7353x2417

                         Email Subscription Date             Website
 62  kristiwhitney@bernard.com        24-03-2022  http://cherry.com/  ,
 'Carey LLC':     Index      Customer Id First Name Last Name    Company          City  \
 95     96  cb8E23e48d22Eae       Karl     Greer  Carey LLC  East Leonard

    Country              Phone 1               Phone 2             Email  \
 95   Chile  (188)169-1674x58692  001-841-293-3519x614  hhart@jensen.com

    Subscription Date                  Website
 95        30-01-2022  http://hayes-perez.com/  ,
 'Carpenter-Cook':     Index      Customer Id First Name Last Name         Company      City  \
 13     14  A08A8aF8BE9FaD4   Kristine       Cox  Carpenter-Cook  Jodyberg

       Country             Phone 1               Phone 2  \
 13  Sri Lanka  786-284-3358x62152  +1-315-627-1796x8074

                        Email Subscription Date                  Website
 13  holdenmiranda@clarke.com        08-02-2021  https://www.brandt.com/  ,
 'Carter-Hancock':     Index      Customer Id First Name Last Name         Company       City  \
 14     15  6fEaA1b7cab7B6C      Faith      Lutz  Carter-Hancock  Burchbury

       Country             Phone 1       Phone 2  \
 14  Singapore  (781)861-7180x8306  207-185-3665

                                 Email Subscription Date                Website
 14  cassieparrish@blevins-chapman.net        26-01-2022  http://stevenson.org/  ,
 'Carter-Strickland':     Index      Customer Id First Name Last Name            Company  \
 88     89  efeb73245CDf1fF     Vernon      Kane  Carter-Strickland

           City Country           Phone 1       Phone 2  \
 88  Thomasfurt   Chile  114-854-1159x555  499-608-4612

                      Email Subscription Date                        Website
 88  hilljesse@barrett.info        15-04-2021  http://www.duffy-hensley.net/  ,
 'Chang, Aguirre and Leblanc':     Index      Customer Id First Name Last Name                     Company  \
 75     76  d40e89dCade7b2F      Debra    Riddle  Chang, Aguirre and Leblanc

           City                       Country                Phone 1  \
 75  Colinhaven  United States Virgin Islands  +1-768-182-6014x14336

           Phone 2                    Email Subscription Date  \
 75  (303)961-4491  shieldskerry@robles.com        11-07-2020

                 Website
 75  http://kaiser.info/  ,
 'Christian, Winters and Ellis':     Index      Customer Id First Name Last Name                       Company  \
 52     53  faCEF517ae7D8eB   Patricia   Goodwin  Christian, Winters and Ellis

          City    Country             Phone 1        Phone 2  \
 52  Cowanfort  Swaziland  322.549.7139x70040  (111)741-4173

                       Email Subscription Date             Website
 52  vaughanchristy@lara.biz        08-03-2021  http://clark.info/  ,
 'Church-Banks':     Index      Customer Id First Name Last Name       Company        City  \
 65     66  fF1b6c9E8Fbf1ff   Fernando   Lambert  Church-Banks  Lake Nancy

       Country       Phone 1     Phone 2                     Email  \
 65  Lithuania  497.829.9038  3863743398  fisherlinda@schaefer.net

    Subscription Date                Website
 65        23-04-2021  https://www.vang.com/  ,
 'Coffey, Lamb and Johnson':     Index      Customer Id First Name Last Name                   Company  \
 81     82  Ebdb6F6F7c90b69   Kathleen     Mckay  Coffey, Lamb and Johnson

               City                           Country        Phone 1  \
 81  Lake Janiceton  Saint Vincent and the Grenadines  (733)910-9968

                Phone 2                              Email Subscription Date  \
 81  (691)247-4128x0665  chloelester@higgins-wilkinson.com        12-09-2021

                          Website
 81  http://www.owens-mooney.com/  ,
 'Combs, Waller and Durham':     Index      Customer Id First Name Last Name                   Company  \
 79     80  A7F85c1DE4dB87f  Alejandro     Blair  Combs, Waller and Durham

           City  Country              Phone 1            Phone 2  \
 79  Thomasland  Iceland  (690)068-4641x51468  555.509.8691x2329

                       Email Subscription Date                       Website
 79  elizabethbarr@ewing.com        19-09-2020  https://mercado-blevins.com/  ,
 'Conway-Mcbride':     Index      Customer Id First Name Last Name         Company  \
 71     72  Ef859092FbEcC07    Richard      Roth  Conway-Mcbride

                 City  Country       Phone 1     Phone 2  \
 71  New Jasmineshire  Morocco  581-440-6539  9857827463

                           Email Subscription Date                  Website
 71  aharper@maddox-townsend.org        23-02-2020  https://www.brooks.com/  ,
 'Costa PLC':     Index      Customer Id First Name  Last Name    Company          City  \
 56     57  c8FE57cBBdCDcb2    Phyllis  Maldonado  Costa PLC  Lake Whitney

              Country     Phone 1               Phone 2  \
 56  Saint Barthelemy  4500370767  001-508-064-6725x017

                       Email Subscription Date                  Website
 56  yhanson@warner-diaz.org        25-01-2021  http://www.bernard.com/  ,
 'Cross PLC':     Index      Customer Id First Name Last Name    Company        City  \
 43     44  D3fC11A9C235Dc6       Luis     Greer  Cross PLC  North Drew

      Country               Phone 1            Phone 2  \
 43  Bulgaria  001-336-025-6849x701  684.698.2911x6092

                              Email Subscription Date  \
 43  bstuart@williamson-mcclure.com        15-05-2022

                           Website
 43  https://fletcher-nielsen.com/  ,
 'Decker-Mcknight':     Index      Customer Id First Name Last Name          Company  \
 89     90  37Ec4B395641c1E       Lori   Flowers  Decker-Mcknight

               City  Country       Phone 1            Phone 2  \
 89  North Joeburgh  Namibia  679.415.1210  945-842-3659x4581

                        Email Subscription Date                        Website
 89  tyrone77@valenzuela.info        09-01-2021  http://www.deleon-crosby.com/  ,
 'Dominguez, Mcmillan and Donovan':    Index      Customer Id First Name Last Name  \
 3      4  5Cef8BFA16c5e3c      Linda     Olsen

                            Company          City Country  \
 3  Dominguez, Mcmillan and Donovan  East Leonard   Chile

                   Phone 1 Phone 2                        Email  \
 3  001-808-617-6467x12895   -9892  stanleyblackwell@benson.org

   Subscription Date                     Website
 3        02-06-2020  http://www.good-lyons.com/  ,
 'Donaldson-Dougherty':     Index      Customer Id First Name Last Name              Company  \
 67     68  a014Ec1b9FccC1E        Tom  Alvarado  Donaldson-Dougherty

                 City   Country             Phone 1            Phone 2  \
 67  South Sophiaberg  Kiribati  (585)606-2980x2258  730-797-3594x5614

                             Email Subscription Date                  Website
 67  nicholsonnina@montgomery.info        18-08-2020  http://odom-massey.com/  ,
 'Fitzgerald-Harrell':     Index      Customer Id First Name Last Name             Company  \
 98     99  c23d1D9EE8DEB0A     Yvonne    Farmer  Fitzgerald-Harrell

             City Country        Phone 1                 Phone 2  \
 98  East Leonard   Chile  (530)311-9786  001-869-452-0943x12424

                              Email Subscription Date               Website
 98  mccarthystephen@horn-green.biz        11-08-2021  http://watkins.info/  ,
 'Fitzpatrick-Lawrence':     Index      Customer Id First Name Last Name               Company  \
 82     83  E8E7e8Cfe516ef0     Hunter    Moreno  Fitzpatrick-Lawrence

             City      Country        Phone 1           Phone 2  \
 82  East Clinton  Isle of Man  (733)833-6754  001-761-013-7121

                         Email Subscription Date             Website
 82  isaac26@benton-finley.com        28-12-2020  http://walls.info/  ,
 'Garcia-Jimenez':     Index      Customer Id First Name Last Name         Company  \
 83     84  78C06E9b6B3DF20       Chad  Davidson  Garcia-Jimenez

                  City Country     Phone 1        Phone 2  \
 83  South Joshuashire    Oman  8275702958  (804)842-4715

                         Email Subscription Date                        Website
 83  justinwalters@jimenez.com        15-11-2021  http://www.garner-oliver.com/  ,
 'Giles Ltd':     Index      Customer Id First Name Last Name    Company         City  \
 25     26  09D7D7C8Fe09aea     Marcus     Moody  Giles Ltd  Kaitlyntown

    Country       Phone 1           Phone 2                            Email  \
 25  Panama  674-677-8623  909-277-5485x566  donnamullins@norris-barrett.org

    Subscription Date                 Website
 25        24-05-2022  https://www.curry.com/  ,
 'Glover and Sons':     Index      Customer Id First Name Last Name          Company  \
 37     38  7a1Ee69F4fF4B4D     Jordan       Gay  Glover and Sons

             City          Country     Phone 1     Phone 2  \
 37  South Walter  Solomon Islands  7208417020  8035336772

                                  Email Subscription Date              Website
 37  tiffanydavies@harris-mcfarland.org        24-02-2021  http://www.lee.org/  ,
 'Graham-Francis':     Index      Customer Id First Name Last Name         Company  \
 12     13  e35426EbDEceaFF     Tracey      Mata  Graham-Francis

                  City Country           Phone 1        Phone 2  \
 12  South Joannamouth    Togo  001-949-844-8787  (855)713-8773

                Email Subscription Date               Website
 12  alex56@walls.org        02-12-2021  http://www.beck.com/  ,
 'Greer and Sons':     Index      Customer Id First Name Last Name         Company          City  \
 22     23  2FB0FAA1d429421    Colleen    Howard  Greer and Sons  Brittanyview

      Country     Phone 1             Phone 2                       Email  \
 22  Paraguay  1935085151  (947)115-7711x5488  rsingleton@ryan-cherry.com

    Subscription Date           Website
 22        19-08-2020  http://paul.biz/  ,
 'Guzman-Brown':     Index      Customer Id First Name Last Name       Company     City  \
 74     75  D01Af0AF7cBbFeA     Regina     Stein  Guzman-Brown  Raystad

             Country                Phone 1                 Phone 2  \
 74  Solomon Islands  001-469-848-0724x4407  001-085-360-4426x00357

                         Email Subscription Date                    Website
 74  zrosario@rojas-hardin.net        15-01-2022  http://www.johnston.info/  ,
 'Henderson Inc':     Index      Customer Id First Name Last Name        Company        City  \
 66     67  2A13F74EAa7DA6c    Makayla    Cannon  Henderson Inc  Georgeport

           Country                 Phone 1       Phone 2  \
 66  New Caledonia  001-215-801-6392x46009  027-609-6460

                      Email Subscription Date                    Website
 66  scottcurtis@hurley.biz        20-01-2020  http://www.velazquez.net/  ,
 'Herrera Group':     Index      Customer Id First Name Last Name        Company         City  \
 33     34  A09AEc6E3bF70eE    Kaitlyn   Santana  Herrera Group  New Kaitlyn

                      Country     Phone 1             Phone 2  \
 33  United States of America  6303643286  447-710-6202x07313

                    Email Subscription Date           Website
 33  georgeross@miles.org        21-09-2021  http://pham.com/  ,
 'Herrera, Shepherd and Underwood':     Index      Customer Id First Name Last Name  \
 44     45  30Dfa48fe5Ede78     Rhonda     Frost

                             Company             City Country        Phone 1  \
 44  Herrera, Shepherd and Underwood  Lake Lindaburgh  Monaco  (127)081-9339

                  Phone 2                     Email Subscription Date  \
 44  +1-431-028-3337x3492  zkrueger@wolf-chavez.net        06-12-2021

                  Website
 44  http://www.khan.com/  ,
 'Hinton, Chaney and Stokes':     Index      Customer Id First Name Last Name                    Company  \
 27     28  b92EBfdF8a3f0E6  Frederick    Harper  Hinton, Chaney and Stokes

                  City      Country               Phone 1       Phone 2  \
 27  South Marissatown  Switzerland  +1-077-121-1558x0687  264.742.7149

                    Email Subscription Date                Website
 27  jacobkhan@bright.biz        26-05-2022  https://callahan.org/  ,
 'Hobbs, Garrett and Sanford':     Index      Customer Id First Name Last Name                     Company  \
 49     50  80F33Fd2AcebF05     Latoya    Mccann  Hobbs, Garrett and Sanford

                City  Country              Phone 1             Phone 2  \
 49  Port Sergiofort  Belarus  (530)287-4548x29481  162-234-0249x32790

                    Email Subscription Date                  Website
 49  bobhammond@barry.biz        02-12-2021  https://www.burton.com/  ,
 'Hoffman, Reed and Mcclain':     Index      Customer Id First Name Last Name                    Company  \
 11     12  CEDec94deE6d69B      Jenna    Dodson  Hoffman, Reed and Mcclain

            City  Country        Phone 1                Phone 2  \
 11  East Andrea  Vietnam  (041)737-3846  +1-556-888-3485x42608

                  Email Subscription Date                  Website
 11  mark42@robbins.com        29-11-2020  http://www.douglas.net/  ,
 'Huerta-Mclean':     Index      Customer Id First Name Last Name        Company       City  \
 38     39  dca4f1D0A0fc5c9      Bruce   Esparza  Huerta-Mclean  Poolefurt

        Country       Phone 1                Phone 2                 Email  \
 38  Montenegro  559-529-4424  001-625-000-7132x0367  preese@frye-vega.com

    Subscription Date                 Website
 38        22-10-2021  http://www.farley.org/  ,
 'Huynh and Sons':     Index      Customer Id First Name Last Name         Company  \
 72     73  F560f2d3cDFb618    Candice    Keller  Huynh and Sons

                City   Country                 Phone 1                 Phone 2  \
 72  East Summerstad  Zimbabwe  001-927-965-8550x92406  001-243-038-4271x53076

                        Email Subscription Date                  Website
 72  buckleycory@odonnell.net        22-08-2020  https://www.lucero.com/  ,
 'Jordan Ltd':     Index      Customer Id First Name Last Name     Company          City  \
 36     37  889eCf90f68c5Da   Nicholas      Sosa  Jordan Ltd  South Hunter

     Country        Phone 1       Phone 2              Email Subscription Date  \
 36  Uruguay  (661)425-6042  975-998-1519  fwolfe@dorsey.com        10-08-2021

                               Website
 36  https://www.fleming-richards.com/  ,
 'Kaufman and Sons':     Index      Customer Id First Name Last Name           Company  \
 41     42  6e5ad5a5e2bB5Ca      Bryan      Dunn  Kaufman and Sons

              City       Country           Phone 1             Phone 2  \
 41  North Jimstad  Burkina Faso  001-710-802-5565  078.699.8982x13881

                         Email Subscription Date                 Website
 41  woodwardandres@phelps.com        08-09-2021  http://www.butler.com/  ,
 'Keller-Coffey':     Index      Customer Id  First Name Last Name        Company         City  \
 70     71  CBCd2Ac8E3eBDF9  Alexandria      Buck  Keller-Coffey  Nicolasfort

    Country             Phone 1             Phone 2              Email  \
 70    Iran  078-900-4760x76668  414-112-8700x68751  lee48@manning.com


In [24]:
gr3=df.groupby('Country').get_group('Chile')
gr3

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Chile,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Chile,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,East Leonard,Chile,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
88,89,efeb73245CDf1fF,Vernon,Kane,Carter-Strickland,Thomasfurt,Chile,114-854-1159x555,499-608-4612,hilljesse@barrett.info,15-04-2021,http://www.duffy-hensley.net/
90,91,5ef6d3eefdD43bE,Nina,Chavez,Byrd-Campbell,Cassidychester,Chile,053-344-3205,+1-330-920-5422x571,elliserica@frank.com,26-03-2020,https://www.pugh.com/
91,92,98b3aeDcC3B9FF3,Shane,Foley,Rocha-Hart,East Leonard,Chile,-1692,001-626-114-5844x55073,nsteele@sparks.com,06-07-2021,https://www.holt-sparks.com/
92,93,aAb6AFc7AfD0fF3,Collin,Ayers,Lamb-Peterson,East Leonard,Chile,404-645-5351x012,001-257-582-8850x8516,dudleyemily@gonzales.biz,29-06-2021,http://www.ruiz.com/
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [25]:
gr3=df.groupby('City').get_group('East Leonard')
gr3

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Leonard,Chile,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,East Leonard,Chile,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",East Leonard,Chile,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,East Leonard,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,25-02-2020,http://www.berger.net/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,East Leonard,Chile,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
91,92,98b3aeDcC3B9FF3,Shane,Foley,Rocha-Hart,East Leonard,Chile,-1692,001-626-114-5844x55073,nsteele@sparks.com,06-07-2021,https://www.holt-sparks.com/
92,93,aAb6AFc7AfD0fF3,Collin,Ayers,Lamb-Peterson,East Leonard,Chile,404-645-5351x012,001-257-582-8850x8516,dudleyemily@gonzales.biz,29-06-2021,http://www.ruiz.com/
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Leonard,Chile,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,East Leonard,Chile,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,East Leonard,Chile,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",East Leonard,Chile,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [28]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv")
df

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4      NaN  20.0
4    5   4300.0   NaN
5    6      NaN  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30      NaN  33.0
30  31  47000.0  54.0

In [30]:
gr7 = df.groupby(by= 'Income')
gr7

In [31]:
gr7.sum()

         ID   Age
Income
4300.0    5   0.0
5000.0    3  19.0
7000.0   15   0.0
9000.0   13  12.0
10000.0   1  22.0
11000.0  14  56.0
12000.0  22  43.0
13000.0   2  30.0
16000.0  25  37.0
17000.0  26  49.0
18000.0  18  52.0
20000.0   7  51.0
23000.0  24   0.0
29000.0  10  44.0
30000.0  20  45.0
32000.0  12  23.0
35000.0  29  51.0
43000.0  27  60.0
47000.0  31  54.0
48000.0   9  45.0
61000.0  17  45.0
70000.0  21  78.0

In [32]:
gr7.mean()

           ID   Age
Income
4300.0    5.0   NaN
5000.0    3.0  19.0
7000.0   15.0   NaN
9000.0   13.0  12.0
10000.0   1.0  22.0
11000.0  14.0  56.0
12000.0  22.0  43.0
13000.0   2.0  30.0
16000.0  25.0  37.0
17000.0  26.0  49.0
18000.0  18.0  52.0
20000.0   7.0  51.0
23000.0  24.0   NaN
29000.0  10.0  44.0
30000.0  20.0  45.0
32000.0  12.0  23.0
35000.0  29.0  51.0
43000.0  13.5  30.0
47000.0  31.0  54.0
48000.0   9.0  45.0
61000.0  17.0  45.0
70000.0  21.0  78.0

In [33]:
gr7.agg(['sum', 'max', 'mean'])

         ID             Age
        sum max  mean   sum   max  mean
Income
4300.0    5   5   5.0   0.0   NaN   NaN
5000.0    3   3   3.0  19.0  19.0  19.0
7000.0   15  15  15.0   0.0   NaN   NaN
9000.0   13  13  13.0  12.0  12.0  12.0
10000.0   1   1   1.0  22.0  22.0  22.0
11000.0  14  14  14.0  56.0  56.0  56.0
12000.0  22  22  22.0  43.0  43.0  43.0
13000.0   2   2   2.0  30.0  30.0  30.0
16000.0  25  25  25.0  37.0  37.0  37.0
17000.0  26  26  26.0  49.0  49.0  49.0
18000.0  18  18  18.0  52.0  52.0  52.0
20000.0   7   7   7.0  51.0  51.0  51.0
23000.0  24  24  24.0   0.0   NaN   NaN
29000.0  10  10  10.0  44.0  44.0  44.0
30000.0  20  20  20.0  45.0  45.0  45.0
32000.0  12  12  12.0  23.0  23.0  23.0
35000.0  29  29  29.0  51.0  51.0  51.0
43000.0  27  19  13.5  60.0  32.0  30.0
47000.0  31  31  31.0  54.0  54.0  54.0
48000.0   9   9   9.0  45.0  45.0  45.0
61000.0  17  17  17.0  45.0  45.0  45.0
70000.0  21  21  21.0  78.0  78.0  78.0