## Handling Missing Values In Pandas ( Python ) :

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours          Marks
0    1  Yes       Ajay Rathod               CSE    2.5             21
1    2  Yes       Vijay Agose                BA    5.1             47
2    3  Yes       Amol Jadhav        Mechanical    3.2             27
3    4  Yes      Surya Mekale        Electrical    8.5  Not Available
4    5  Yes       Lakhan More               CSE    3.5             30
5    6   No       Suyog Mohod               CSE    1.5             20
6    7   No    Santosh Rathod       Electrician    9.2             88
7    8   No    Saurabh Jadhav        Civil Exam    5.5            NaN
8    9   No      Suraj jadhav           D pharm    8.3  Not Available
9   10   No     Kishor Jadhav    12 th pass out    2.7            NaN
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7             81
11  12   No  Vaishnavi Chavan             CSE-B    5.9             81
12  13  Yes      Rohini Agose           BA & MA    4.5             81
13  14  Yes      Sunil Jadhav              BAMS    3.3             81
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1             81
15  16   No       Namdev Zate         MPSC EXAM    8.9             81
16  17   No     Akash Sakhare        Civil Exam    2.5            NaN
17  18   No     Praful Jadhav           D pharm    1.9  Not Available
18  19  Yes       Amol Ambore        Civil Engg    6.1            NaN
19  20  Yes  Vishal Jamvankar            AIML-C    7.4            NaN
20  21   No     Parth Dangare            AIML-B    2.7             30
21  22  Yes     Manisha Pande    12 th pass out    4.8             54
22  23   No    Lata Khachakad    12 th pass out    3.8             35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9             76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8             86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv",na_values = 'Not Available')
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5   21.0
1    2  Yes       Vijay Agose                BA    5.1   47.0
2    3  Yes       Amol Jadhav        Mechanical    3.2   27.0
3    4  Yes      Surya Mekale        Electrical    8.5    NaN
4    5  Yes       Lakhan More               CSE    3.5   30.0
5    6   No       Suyog Mohod               CSE    1.5   20.0
6    7   No    Santosh Rathod       Electrician    9.2   88.0
7    8   No    Saurabh Jadhav        Civil Exam    5.5    NaN
8    9   No      Suraj jadhav           D pharm    8.3    NaN
9   10   No     Kishor Jadhav    12 th pass out    2.7    NaN
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7   81.0
11  12   No  Vaishnavi Chavan             CSE-B    5.9   81.0
12  13  Yes      Rohini Agose           BA & MA    4.5   81.0
13  14  Yes      Sunil Jadhav              BAMS    3.3   81.0
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1   81.0
15  16   No       Namdev Zate         MPSC EXAM    8.9   81.0
16  17   No     Akash Sakhare        Civil Exam    2.5    NaN
17  18   No     Praful Jadhav           D pharm    1.9    NaN
18  19  Yes       Amol Ambore        Civil Engg    6.1    NaN
19  20  Yes  Vishal Jamvankar            AIML-C    7.4    NaN
20  21   No     Parth Dangare            AIML-B    2.7   30.0
21  22  Yes     Manisha Pande    12 th pass out    4.8   54.0
22  23   No    Lata Khachakad    12 th pass out    3.8   35.0
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9   76.0
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8   86.0

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR       date              Nmes            Trades  Hours          Marks
0    1        Yes       Ajay Rathod               CSE    2.5             21
1    2        Yes       Vijay Agose                BA    5.1             47
2    3        Yes       Amol Jadhav        Mechanical    3.2             27
3    4  No Values      Surya Mekale        Electrical    8.5  Not Available
4    5        Yes       Lakhan More               CSE    3.5             30
5    6         No       Suyog Mohod               CSE    1.5             20
6    7         No    Santosh Rathod       Electrician    9.2             88
7    8  No Values    Saurabh Jadhav        Civil Exam    5.5            NaN
8    9         No      Suraj jadhav           D pharm    8.3  Not Available
9   10         No     Kishor Jadhav    12 th pass out    2.7            NaN
10  11  No Values      Divya Jadhav  Electonics & CSE    7.7             81
11  12         No  Vaishnavi Chavan             CSE-B    5.9             81
12  13        Yes      Rohini Agose           BA & MA    4.5             81
13  14        Yes      Sunil Jadhav              BAMS    3.3             81
14  15        Yes  Jerrysing Rathod        Aramy Exam    1.1             81
15  16         No       Namdev Zate         MPSC EXAM    8.9             81
16  17         No     Akash Sakhare        Civil Exam    2.5            NaN
17  18  No Values     Praful Jadhav           D pharm    1.9  Not Available
18  19        Yes       Amol Ambore        Civil Engg    6.1            NaN
19  20        Yes  Vishal Jamvankar            AIML-C    7.4            NaN
20  21         No     Parth Dangare            AIML-B    2.7             30
21  22        Yes     Manisha Pande    12 th pass out    4.8             54
22  23         No    Lata Khachakad    12 th pass out    3.8             35
23  24        Yes     Ganesh Jadhav     Lauary Driver    6.9             76
24  25         No    Dhanraj Jadhav     Bike Mechanic    7.8             86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv",na_values = ['Not Available', 'No Values'])
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5   21.0
1    2  Yes       Vijay Agose                BA    5.1   47.0
2    3  Yes       Amol Jadhav        Mechanical    3.2   27.0
3    4  NaN      Surya Mekale        Electrical    8.5    NaN
4    5  Yes       Lakhan More               CSE    3.5   30.0
5    6   No       Suyog Mohod               CSE    1.5   20.0
6    7   No    Santosh Rathod       Electrician    9.2   88.0
7    8  NaN    Saurabh Jadhav        Civil Exam    5.5    NaN
8    9   No      Suraj jadhav           D pharm    8.3    NaN
9   10   No     Kishor Jadhav    12 th pass out    2.7    NaN
10  11  NaN      Divya Jadhav  Electonics & CSE    7.7   81.0
11  12   No  Vaishnavi Chavan             CSE-B    5.9   81.0
12  13  Yes      Rohini Agose           BA & MA    4.5   81.0
13  14  Yes      Sunil Jadhav              BAMS    3.3   81.0
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1   81.0
15  16   No       Namdev Zate         MPSC EXAM    8.9   81.0
16  17   No     Akash Sakhare        Civil Exam    2.5    NaN
17  18  NaN     Praful Jadhav           D pharm    1.9    NaN
18  19  Yes       Amol Ambore        Civil Engg    6.1    NaN
19  20  Yes  Vishal Jamvankar            AIML-C    7.4    NaN
20  21   No     Parth Dangare            AIML-B    2.7   30.0
21  22  Yes     Manisha Pande    12 th pass out    4.8   54.0
22  23   No    Lata Khachakad    12 th pass out    3.8   35.0
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9   76.0
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8   86.0

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR       date              Nmes            Trades  Hours          Marks
0    1        Yes       Ajay Rathod               CSE    2.5             21
1    2        Yes       Vijay Agose                BA    5.1             47
2    3        Yes       Amol Jadhav        Mechanical    3.2             27
3    4  No Values      Surya Mekale        Electrical    8.5  Not Available
4    5        Yes       Lakhan More               CSE    3.5             30
5    6         No       Suyog Mohod               CSE    1.5             20
6    7         No    Santosh Rathod       Electrician    9.2             88
7    8  No Values    Saurabh Jadhav        Civil Exam    5.5            NaN
8    9         No      Suraj jadhav           D pharm    8.3  Not Available
9   10         No     Kishor Jadhav    12 th pass out    2.7            NaN
10  11  No Values      Divya Jadhav  Electonics & CSE    7.7             81
11  12         No  Vaishnavi Chavan             CSE-B    5.9             81
12  13        Yes      Rohini Agose           BA & MA    4.5             81
13  14        Yes      Sunil Jadhav              BAMS    3.3             81
14  15        Yes  Jerrysing Rathod        Aramy Exam    1.1             81
15  16         No       Namdev Zate         MPSC EXAM    8.9             81
16  17         No     Akash Sakhare        Civil Exam    2.5            NaN
17  18  No Values     Praful Jadhav           D pharm    1.9  Not Available
18  19        Yes       Amol Ambore        Civil Engg    6.1            NaN
19  20        Yes  Vishal Jamvankar            AIML-C    7.4            NaN
20  21         No     Parth Dangare            AIML-B    2.7             30
21  22        Yes     Manisha Pande    12 th pass out    4.8             54
22  23         No    Lata Khachakad    12 th pass out    3.8             35
23  24        Yes     Ganesh Jadhav     Lauary Driver    6.9             76
24  25         No    Dhanraj Jadhav     Bike Mechanic    7.8             86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", na_values = {'date': 'No Values', 'Marks': 'Not Available'})
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5   21.0
1    2  Yes       Vijay Agose                BA    5.1   47.0
2    3  Yes       Amol Jadhav        Mechanical    3.2   27.0
3    4  NaN      Surya Mekale        Electrical    8.5    NaN
4    5  Yes       Lakhan More               CSE    3.5   30.0
5    6   No       Suyog Mohod               CSE    1.5   20.0
6    7   No    Santosh Rathod       Electrician    9.2   88.0
7    8  NaN    Saurabh Jadhav        Civil Exam    5.5    NaN
8    9   No      Suraj jadhav           D pharm    8.3    NaN
9   10   No     Kishor Jadhav    12 th pass out    2.7    NaN
10  11  NaN      Divya Jadhav  Electonics & CSE    7.7   81.0
11  12   No  Vaishnavi Chavan             CSE-B    5.9   81.0
12  13  Yes      Rohini Agose           BA & MA    4.5   81.0
13  14  Yes      Sunil Jadhav              BAMS    3.3   81.0
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1   81.0
15  16   No       Namdev Zate         MPSC EXAM    8.9   81.0
16  17   No     Akash Sakhare        Civil Exam    2.5    NaN
17  18  NaN     Praful Jadhav           D pharm    1.9    NaN
18  19  Yes       Amol Ambore        Civil Engg    6.1    NaN
19  20  Yes  Vishal Jamvankar            AIML-C    7.4    NaN
20  21   No     Parth Dangare            AIML-B    2.7   30.0
21  22  Yes     Manisha Pande    12 th pass out    4.8   54.0
22  23   No    Lata Khachakad    12 th pass out    3.8   35.0
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9   76.0
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8   86.0

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR       date              Nmes            Trades  Hours          Marks
0    1        Yes       Ajay Rathod               CSE    2.5             21
1    2        Yes       Vijay Agose                BA    5.1             47
2    3        Yes       Amol Jadhav        Mechanical    3.2             27
3    4  No Values      Surya Mekale        Electrical    8.5  Not Available
4    5        Yes       Lakhan More               CSE    3.5             30
5    6       #N?A       Suyog Mohod               CSE    1.5             20
6    7         No    Santosh Rathod       Electrician    9.2             88
7    8  No Values    Saurabh Jadhav        Civil Exam    5.5            NaN
8    9         No      Suraj jadhav           D pharm    8.3  Not Available
9   10         No     Kishor Jadhav    12 th pass out    2.7            NaN
10  11  No Values      Divya Jadhav  Electonics & CSE    7.7             81
11  12         No  Vaishnavi Chavan             CSE-B    5.9             81
12  13        Yes      Rohini Agose           BA & MA    4.5             81
13  14        Yes      Sunil Jadhav              BAMS    3.3             81
14  15        Yes  Jerrysing Rathod        Aramy Exam    1.1             81
15  16         No       Namdev Zate         MPSC EXAM    8.9             81
16  17         No     Akash Sakhare        Civil Exam    2.5            NaN
17  18  No Values     Praful Jadhav           D pharm    1.9  Not Available
18  19        Yes       Amol Ambore        Civil Engg    6.1            NaN
19  20        Yes  Vishal Jamvankar            AIML-C    7.4            NaN
20  21        NaN     Parth Dangare            AIML-B    2.7             30
21  22        Yes     Manisha Pande    12 th pass out    4.8             54
22  23         No    Lata Khachakad    12 th pass out    3.8             35
23  24        Yes     Ganesh Jadhav     Lauary Driver    6.9             76
24  25         No    Dhanraj Jadhav     Bike Mechanic    7.8             86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", keep_default_na =False)
df

    SR       date              Nmes            Trades  Hours          Marks
0    1        Yes       Ajay Rathod               CSE    2.5             21
1    2        Yes       Vijay Agose                BA    5.1             47
2    3        Yes       Amol Jadhav        Mechanical    3.2             27
3    4  No Values      Surya Mekale        Electrical    8.5  Not Available
4    5        Yes       Lakhan More               CSE    3.5             30
5    6       #N?A       Suyog Mohod               CSE    1.5             20
6    7         No    Santosh Rathod       Electrician    9.2             88
7    8  No Values    Saurabh Jadhav        Civil Exam    5.5           NULL
8    9         No      Suraj jadhav           D pharm    8.3  Not Available
9   10         No     Kishor Jadhav    12 th pass out    2.7
10  11  No Values      Divya Jadhav  Electonics & CSE    7.7             81
11  12         No  Vaishnavi Chavan             CSE-B    5.9             81
12  13        Yes      Rohini Agose           BA & MA    4.5             81
13  14        Yes      Sunil Jadhav              BAMS    3.3             81
14  15        Yes  Jerrysing Rathod        Aramy Exam    1.1             81
15  16         No       Namdev Zate         MPSC EXAM    8.9             81
16  17         No     Akash Sakhare        Civil Exam    2.5
17  18  No Values     Praful Jadhav           D pharm    1.9  Not Available
18  19        Yes       Amol Ambore        Civil Engg    6.1
19  20        Yes  Vishal Jamvankar            AIML-C    7.4           NULL
20  21       #N/A     Parth Dangare            AIML-B    2.7             30
21  22        Yes     Manisha Pande    12 th pass out    4.8             54
22  23         No    Lata Khachakad    12 th pass out    3.8             35
23  24        Yes     Ganesh Jadhav     Lauary Driver    6.9             76
24  25         No    Dhanraj Jadhav     Bike Mechanic    7.8             86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", keep_default_na =True)
df

    SR       date              Nmes            Trades  Hours          Marks
0    1        Yes       Ajay Rathod               CSE    2.5             21
1    2        Yes       Vijay Agose                BA    5.1             47
2    3        Yes       Amol Jadhav        Mechanical    3.2             27
3    4  No Values      Surya Mekale        Electrical    8.5  Not Available
4    5        Yes       Lakhan More               CSE    3.5             30
5    6       #N?A       Suyog Mohod               CSE    1.5             20
6    7         No    Santosh Rathod       Electrician    9.2             88
7    8  No Values    Saurabh Jadhav        Civil Exam    5.5            NaN
8    9         No      Suraj jadhav           D pharm    8.3  Not Available
9   10         No     Kishor Jadhav    12 th pass out    2.7            NaN
10  11  No Values      Divya Jadhav  Electonics & CSE    7.7             81
11  12         No  Vaishnavi Chavan             CSE-B    5.9             81
12  13        Yes      Rohini Agose           BA & MA    4.5             81
13  14        Yes      Sunil Jadhav              BAMS    3.3             81
14  15        Yes  Jerrysing Rathod        Aramy Exam    1.1             81
15  16         No       Namdev Zate         MPSC EXAM    8.9             81
16  17         No     Akash Sakhare        Civil Exam    2.5            NaN
17  18  No Values     Praful Jadhav           D pharm    1.9  Not Available
18  19        Yes       Amol Ambore        Civil Engg    6.1            NaN
19  20        Yes  Vishal Jamvankar            AIML-C    7.4            NaN
20  21        NaN     Parth Dangare            AIML-B    2.7             30
21  22        Yes     Manisha Pande    12 th pass out    4.8             54
22  23         No    Lata Khachakad    12 th pass out    3.8             35
23  24        Yes     Ganesh Jadhav     Lauary Driver    6.9             76
24  25         No    Dhanraj Jadhav     Bike Mechanic    7.8             86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  No       Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6  Yes       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     92
8    9   No      Suraj jadhav           D pharm    8.3     54
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     81
11  12   No  Vaishnavi Chavan             CSE-B    5.9     81
12  13  Yes      Rohini Agose           BA & MA    4.5     81
13  14  Yes      Sunil Jadhav              BAMS    3.3     45
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1     15
15  16   No       Namdev Zate         MPSC EXAM    8.9     81
16  17   No     Akash Sakhare        Civil Exam    2.5     22
17  18   No     Praful Jadhav           D pharm    1.9     12
18  19  Yes       Amol Ambore        Civil Engg    6.1     76
19  20  Yes  Vishal Jamvankar            AIML-C    7.4     88
20  21  Yes     Parth Dangare            AIML-B    2.7     30
21  22  Yes     Manisha Pande    12 th pass out    4.8     54
22  23   No    Lata Khachakad    12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", na_filter =False)
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  No       Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6  Yes       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     92
8    9   No      Suraj jadhav           D pharm    8.3     54
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     81
11  12   No  Vaishnavi Chavan             CSE-B    5.9     81
12  13  Yes      Rohini Agose           BA & MA    4.5     81
13  14  Yes      Sunil Jadhav              BAMS    3.3     45
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1     15
15  16   No       Namdev Zate         MPSC EXAM    8.9     81
16  17   No     Akash Sakhare        Civil Exam    2.5     22
17  18   No     Praful Jadhav           D pharm    1.9     12
18  19  Yes       Amol Ambore        Civil Engg    6.1     76
19  20  Yes  Vishal Jamvankar            AIML-C    7.4     88
20  21  Yes     Parth Dangare            AIML-B    2.7     30
21  22  Yes     Manisha Pande    12 th pass out    4.8     54
22  23   No    Lata Khachakad    12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

## Part 2

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5   21.0
1    2  Yes       Vijay Agose                BA    5.1   47.0
2    3  Yes       Amol Jadhav        Mechanical    3.2   27.0
3    4  No       Surya Mekale        Electrical    8.5   75.0
4    5  Yes       Lakhan More               CSE    3.5   30.0
5    6  Yes       Suyog Mohod               CSE    NaN   20.0
6    7   No    Santosh Rathod       Electrician    9.2    NaN
7    8   No    Saurabh Jadhav        Civil Exam    NaN    NaN
8    9   No      Suraj jadhav           D pharm    8.3   54.0
9   10   No     Kishor Jadhav    12 th pass out    2.7   25.0
10  11  Yes      Divya Jadhav  Electonics & CSE    NaN   81.0
11  12   No  Vaishnavi Chavan             CSE-B    5.9   81.0
12  13  Yes      Rohini Agose           BA & MA    4.5   81.0
13  14  Yes      Sunil Jadhav              BAMS    3.3    NaN
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1    NaN
15  16   No       Namdev Zate         MPSC EXAM    8.9   81.0
16  17   No     Akash Sakhare        Civil Exam    NaN   22.0
17  18   No     Praful Jadhav           D pharm    1.9   12.0
18  19  Yes       Amol Ambore        Civil Engg    6.1   76.0
19  20  Yes  Vishal Jamvankar            AIML-C    7.4   88.0
20  21  Yes     Parth Dangare            AIML-B    2.7   30.0
21  22  Yes     Manisha Pande    12 th pass out    NaN   54.0
22  23   No    Lata Khachakad    12 th pass out    3.8   35.0
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9   76.0
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8   86.0

In [ ]:
df.isnull()

       SR   date   Nmes  Trades  Hours  Marks
0   False  False  False   False  False  False
1   False  False  False   False  False  False
2   False  False  False   False  False  False
3   False  False  False   False  False  False
4   False  False  False   False  False  False
5   False  False  False   False   True  False
6   False  False  False   False  False   True
7   False  False  False   False   True   True
8   False  False  False   False  False  False
9   False  False  False   False  False  False
10  False  False  False   False   True  False
11  False  False  False   False  False  False
12  False  False  False   False  False  False
13  False  False  False   False  False   True
14  False  False  False   False  False   True
15  False  False  False   False  False  False
16  False  False  False   False   True  False
17  False  False  False   False  False  False
18  False  False  False   False  False  False
19  False  False  False   False  False  False
20  False  False  False   False  False  False
21  False  False  False   False   True  False
22  False  False  False   False  False  False
23  False  False  False   False  False  False
24  False  False  False   False  False  False

In [ ]:
df.isnull().sum()

SR        0
date      0
Nmes      0
Trades    0
Hours     5
Marks     4
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(9)

In [ ]:
df = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5   21.0
1    2  Yes       Vijay Agose                BA    5.1   47.0
2    3  Yes       Amol Jadhav        Mechanical    3.2   27.0
3    4  No       Surya Mekale        Electrical    8.5   75.0
4    5  Yes       Lakhan More               CSE    3.5   30.0
5    6  Yes       Suyog Mohod               CSE    NaN   20.0
6    7   No    Santosh Rathod       Electrician    9.2    NaN
7    8   No    Saurabh Jadhav        Civil Exam    NaN    NaN
8    9   No      Suraj jadhav           D pharm    8.3   54.0
9   10   No     Kishor Jadhav    12 th pass out    2.7   25.0
10  11  Yes      Divya Jadhav  Electonics & CSE    NaN   81.0
11  12   No  Vaishnavi Chavan             CSE-B    5.9   81.0
12  13  Yes      Rohini Agose           BA & MA    4.5   81.0
13  14  Yes      Sunil Jadhav              BAMS    3.3    NaN
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1    NaN
15  16   No       Namdev Zate         MPSC EXAM    8.9   81.0
16  17   No     Akash Sakhare        Civil Exam    NaN   22.0
17  18   No     Praful Jadhav           D pharm    1.9   12.0
18  19  Yes       Amol Ambore        Civil Engg    6.1   76.0
19  20  Yes  Vishal Jamvankar            AIML-C    7.4   88.0
20  21  Yes     Parth Dangare            AIML-B    2.7   30.0
21  22  Yes     Manisha Pande    12 th pass out    NaN   54.0
22  23   No    Lata Khachakad    12 th pass out    3.8   35.0
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9   76.0
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8   86.0

In [ ]:
df.notnull()

      SR  date  Nmes  Trades  Hours  Marks
0   True  True  True    True   True   True
1   True  True  True    True   True   True
2   True  True  True    True   True   True
3   True  True  True    True   True   True
4   True  True  True    True   True   True
5   True  True  True    True  False   True
6   True  True  True    True   True  False
7   True  True  True    True  False  False
8   True  True  True    True   True   True
9   True  True  True    True   True   True
10  True  True  True    True  False   True
11  True  True  True    True   True   True
12  True  True  True    True   True   True
13  True  True  True    True   True  False
14  True  True  True    True   True  False
15  True  True  True    True   True   True
16  True  True  True    True  False   True
17  True  True  True    True   True   True
18  True  True  True    True   True   True
19  True  True  True    True   True   True
20  True  True  True    True   True   True
21  True  True  True    True  False   True
22  True  True  True    True   True   True
23  True  True  True    True   True   True
24  True  True  True    True   True   True

In [ ]:
df.notnull().sum()

SR        25
date      25
Nmes      25
Trades    25
Hours     20
Marks     21
dtype: int64

In [ ]:
df.notnull().sum().sum()

np.int64(141)

Series :

In [ ]:
import numpy as np
sr = pd.Series([1,2,3,np.nan,4,np.nan])
sr

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [ ]:
sr.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
sr.isnull().sum()

np.int64(2)