Pandas Replace () :

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\ajayr\\Downloads\\archive (2)\\Income.csv")
df

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4   4000.0  20.0
4    5   4300.0   NaN
5    6  45000.0  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30  30000.0  33.0
30  31  47000.0  54.0

In [11]:
df.replace(to_replace='NaN', value='200122')

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4   4000.0  20.0
4    5   4300.0   NaN
5    6  45000.0  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30  30000.0  33.0
30  31  47000.0  54.0

In [12]:
df.replace('Italy', 'India')

    ID   Income   Age
0    1  10000.0  22.0
1    2  13000.0  30.0
2    3   5000.0  19.0
3    4   4000.0  20.0
4    5   4300.0   NaN
5    6  45000.0  33.0
6    7  20000.0  51.0
7    8  43000.0  28.0
8    9  48000.0  45.0
9   10  29000.0  44.0
10  11      NaN  31.0
11  12  32000.0  23.0
12  13   9000.0  12.0
13  14  11000.0  56.0
14  15   7000.0   NaN
15  16      NaN  32.0
16  17  61000.0  45.0
17  18  18000.0  52.0
18  19  43000.0  32.0
19  20  30000.0  45.0
20  21  70000.0  78.0
21  22  12000.0  43.0
22  23      NaN  56.0
23  24  23000.0   NaN
24  25  16000.0  37.0
25  26  17000.0  49.0
26  27      NaN  62.0
27  28      NaN  57.0
28  29  35000.0  51.0
29  30  30000.0  33.0
30  31  47000.0  54.0

In [ ]:
df.replace(2.8, 3.8)

      iso_code      country  year     sex age_group  suicide_rate
0          AFG  Afghanistan  2000    male       ALL      5.793457
1          AFG  Afghanistan  2000    both       ALL      4.356148
2          AFG  Afghanistan  2000  female       ALL      2.910393
3          AFG  Afghanistan  2001    male       ALL      5.831328
4          AFG  Afghanistan  2001    both       ALL      4.383031
...        ...          ...   ...     ...       ...           ...
18310      ZWE     Zimbabwe  2021    male     20_29     24.592566
18311      ZWE     Zimbabwe  2021    male     15_29     22.297359
18312      ZWE     Zimbabwe  2021  female     15_19      9.802394
18313      ZWE     Zimbabwe  2021    both     50_59     49.098438
18314      ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace(['AFG'], 'Afanistan')

        iso_code      country  year     sex age_group  suicide_rate
0      Afanistan  Afghanistan  2000    male       ALL      5.793457
1      Afanistan  Afghanistan  2000    both       ALL      4.356148
2      Afanistan  Afghanistan  2000  female       ALL      2.910393
3      Afanistan  Afghanistan  2001    male       ALL      5.831328
4      Afanistan  Afghanistan  2001    both       ALL      4.383031
...          ...          ...   ...     ...       ...           ...
18310        ZWE     Zimbabwe  2021    male     20_29     24.592566
18311        ZWE     Zimbabwe  2021    male     15_29     22.297359
18312        ZWE     Zimbabwe  2021  female     15_19      9.802394
18313        ZWE     Zimbabwe  2021    both     50_59     49.098438
18314        ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace(['AFG','ZWE'], [1000050,1000550])

      iso_code      country  year     sex age_group  suicide_rate
0      1000050  Afghanistan  2000    male       ALL      5.793457
1      1000050  Afghanistan  2000    both       ALL      4.356148
2      1000050  Afghanistan  2000  female       ALL      2.910393
3      1000050  Afghanistan  2001    male       ALL      5.831328
4      1000050  Afghanistan  2001    both       ALL      4.383031
...        ...          ...   ...     ...       ...           ...
18310  1000550     Zimbabwe  2021    male     20_29     24.592566
18311  1000550     Zimbabwe  2021    male     15_29     22.297359
18312  1000550     Zimbabwe  2021  female     15_19      9.802394
18313  1000550     Zimbabwe  2021    both     50_59     49.098438
18314  1000550     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace({'age_group': 'ALL'}, 'None')

      iso_code      country  year     sex age_group  suicide_rate
0          AFG  Afghanistan  2000    male      None      5.793457
1          AFG  Afghanistan  2000    both      None      4.356148
2          AFG  Afghanistan  2000  female      None      2.910393
3          AFG  Afghanistan  2001    male      None      5.831328
4          AFG  Afghanistan  2001    both      None      4.383031
...        ...          ...   ...     ...       ...           ...
18310      ZWE     Zimbabwe  2021    male     20_29     24.592566
18311      ZWE     Zimbabwe  2021    male     15_29     22.297359
18312      ZWE     Zimbabwe  2021  female     15_19      9.802394
18313      ZWE     Zimbabwe  2021    both     50_59     49.098438
18314      ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace({'age_group': 'ALL', 'year': 2001}, 'None')

      iso_code      country  year     sex age_group  suicide_rate
0          AFG  Afghanistan  2000    male      None      5.793457
1          AFG  Afghanistan  2000    both      None      4.356148
2          AFG  Afghanistan  2000  female      None      2.910393
3          AFG  Afghanistan  None    male      None      5.831328
4          AFG  Afghanistan  None    both      None      4.383031
...        ...          ...   ...     ...       ...           ...
18310      ZWE     Zimbabwe  2021    male     20_29     24.592566
18311      ZWE     Zimbabwe  2021    male     15_29     22.297359
18312      ZWE     Zimbabwe  2021  female     15_19      9.802394
18313      ZWE     Zimbabwe  2021    both     50_59     49.098438
18314      ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace('[A-Z]',0)

      iso_code      country  year     sex age_group  suicide_rate
0          AFG  Afghanistan  2000    male       ALL      5.793457
1          AFG  Afghanistan  2000    both       ALL      4.356148
2          AFG  Afghanistan  2000  female       ALL      2.910393
3          AFG  Afghanistan  2001    male       ALL      5.831328
4          AFG  Afghanistan  2001    both       ALL      4.383031
...        ...          ...   ...     ...       ...           ...
18310      ZWE     Zimbabwe  2021    male     20_29     24.592566
18311      ZWE     Zimbabwe  2021    male     15_29     22.297359
18312      ZWE     Zimbabwe  2021  female     15_19      9.802394
18313      ZWE     Zimbabwe  2021    both     50_59     49.098438
18314      ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace({'country': '[A-Za-z]'}, 0, regex=True)

      iso_code country  year     sex age_group  suicide_rate
0          AFG       0  2000    male       ALL      5.793457
1          AFG       0  2000    both       ALL      4.356148
2          AFG       0  2000  female       ALL      2.910393
3          AFG       0  2001    male       ALL      5.831328
4          AFG       0  2001    both       ALL      4.383031
...        ...     ...   ...     ...       ...           ...
18310      ZWE       0  2021    male     20_29     24.592566
18311      ZWE       0  2021    male     15_29     22.297359
18312      ZWE       0  2021  female     15_19      9.802394
18313      ZWE       0  2021    both     50_59     49.098438
18314      ZWE       0  2021    male     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.replace('[A-Za-z]', 0, regex=True)

      iso_code country  year sex age_group  suicide_rate
0            0       0  2000   0         0      5.793457
1            0       0  2000   0         0      4.356148
2            0       0  2000   0         0      2.910393
3            0       0  2001   0         0      5.831328
4            0       0  2001   0         0      4.383031
...        ...     ...   ...  ..       ...           ...
18310        0       0  2021   0     20_29     24.592566
18311        0       0  2021   0     15_29     22.297359
18312        0       0  2021   0     15_19      9.802394
18313        0       0  2021   0     50_59     49.098438
18314        0       0  2021   0     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df.ffill()

      iso_code country  year sex age_group  suicide_rate
0            0       0  2000   0         0      5.793457
1            0       0  2000   0         0      4.356148
2            0       0  2000   0         0      2.910393
3            0       0  2001   0         0      5.831328
4            0       0  2001   0         0      4.383031
...        ...     ...   ...  ..       ...           ...
18310        0       0  2021   0     20_29     24.592566
18311        0       0  2021   0     15_29     22.297359
18312        0       0  2021   0     15_19      9.802394
18313        0       0  2021   0     50_59     49.098438
18314        0       0  2021   0     10_19      9.177570

[18315 rows x 6 columns]

In [ ]:
df=pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Docs\\GitHub\\Royal-Python\\Royal Machine Learning\\tassi-di-suicidio-globali-per-paese-2000-2021.csv")

print(df.ffill()) # forward fill
print(df.bfill())

      iso_code      country  year     sex age_group  suicide_rate
0          AFG  Afghanistan  2000    male       ALL      5.793457
1          AFG  Afghanistan  2000    both       ALL      4.356148
2          AFG  Afghanistan  2000  female       ALL      2.910393
3          AFG  Afghanistan  2001    male       ALL      5.831328
4          AFG  Afghanistan  2001    both       ALL      4.383031
...        ...          ...   ...     ...       ...           ...
18310      ZWE     Zimbabwe  2021    male     20_29     24.592566
18311      ZWE     Zimbabwe  2021    male     15_29     22.297359
18312      ZWE     Zimbabwe  2021  female     15_19      9.802394
18313      ZWE     Zimbabwe  2021    both     50_59     49.098438
18314      ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]
      iso_code      country  year     sex age_group  suicide_rate
0          AFG  Afghanistan  2000    male       ALL      5.793457
1          AFG  Afghanistan  2000    both       ALL      4.356148
2          AFG  Afghanistan  2000  female       ALL      2.910393
3          AFG  Afghanistan  2001    male       ALL      5.831328
4          AFG  Afghanistan  2001    both       ALL      4.383031
...        ...          ...   ...     ...       ...           ...
18310      ZWE     Zimbabwe  2021    male     20_29     24.592566
18311      ZWE     Zimbabwe  2021    male     15_29     22.297359
18312      ZWE     Zimbabwe  2021  female     15_19      9.802394
18313      ZWE     Zimbabwe  2021    both     50_59     49.098438
18314      ZWE     Zimbabwe  2021    male     10_19      9.177570

[18315 rows x 6 columns]