## DropNA :

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\Diabetes Missing Data.csv")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [3]:
df.dropna()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0
13,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59.0,1.0
...,...,...,...,...,...,...,...,...,...
753,0.0,181.0,88.0,44.0,510.0,43.3,0.222,26.0,1.0
755,1.0,128.0,88.0,39.0,110.0,36.5,1.057,37.0,1.0
760,2.0,88.0,58.0,26.0,16.0,28.4,0.766,22.0,0.0
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0

In [4]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[768 rows x 0 columns]

In [5]:
df.dropna(how='any')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0
13,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59.0,1.0
...,...,...,...,...,...,...,...,...,...
753,0.0,181.0,88.0,44.0,510.0,43.3,0.222,26.0,1.0
755,1.0,128.0,88.0,39.0,110.0,36.5,1.057,37.0,1.0
760,2.0,88.0,58.0,26.0,16.0,28.4,0.766,22.0,0.0
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0

In [6]:
df.dropna(axis=1,how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[768 rows x 0 columns]

In [7]:
df.dropna(how='all')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [8]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\Diabetes Missing Data.csv")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [9]:
df.dropna(how='all')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [10]:
df.head(10)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
5,5.0,116.0,74.0,NaN,NaN,25.6,0.201,30.0,0.0
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
7,10.0,115.0,NaN,NaN,NaN,35.3,0.134,29.0,0.0
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0
9,8.0,125.0,96.0,NaN,NaN,NaN,0.232,54.0,1.0

Tresh Method

In [11]:
df.dropna(thresh =5)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [12]:
df = pd.read_csv("C:\\Users\\ajayr\\Downloads\\Diabetes Missing Data.csv")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [13]:
df.dropna(subset='Skin_Fold')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
...,...,...,...,...,...,...,...,...,...
761,9.0,170.0,74.0,31.0,NaN,44.0,0.403,43.0,1.0
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [14]:
df.dropna(subset='Serum_Insulin')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0
13,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59.0,1.0
...,...,...,...,...,...,...,...,...,...
753,0.0,181.0,88.0,44.0,510.0,43.3,0.222,26.0,1.0
755,1.0,128.0,88.0,39.0,110.0,36.5,1.057,37.0,1.0
760,2.0,88.0,58.0,26.0,16.0,28.4,0.766,22.0,0.0
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0

In [15]:
df.tail()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [16]:
df.dropna(inplace=True)
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
6,3.0,78.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
8,2.0,197.0,70.0,45.0,543.0,30.5,0.158,53.0,1.0
13,1.0,189.0,60.0,23.0,846.0,30.1,0.398,59.0,1.0
...,...,...,...,...,...,...,...,...,...
753,0.0,181.0,88.0,44.0,510.0,43.3,0.222,26.0,1.0
755,1.0,128.0,88.0,39.0,110.0,36.5,1.057,37.0,1.0
760,2.0,88.0,58.0,26.0,16.0,28.4,0.766,22.0,0.0
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0

## Pandas Fillna() :

In [17]:
import pandas as pd

In [18]:
ar = pd.read_csv("C:\\Users\\ajayr\\Downloads\\Diabetes Missing Data.csv")
ar

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [19]:
ar.fillna(0)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0

In [20]:
ar.fillna(2)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,2.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,2.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,2.0,2.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,2.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,2.0,2.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,2.0,30.4,0.315,23.0,0.0

In [21]:
ar.fillna({'Serum_Insulin': 'none', 'Skin_Fold' : 0, 'BMI': 0 })

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,none,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,none,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,none,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,none,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,none,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,none,30.4,0.315,23.0,0.0

In [22]:
ar = pd.read_csv("C:\\Users\\ajayr\\Downloads\\Diabetes Missing Data.csv")

print(ar.ffill()) # forward fill
print(ar.bfill())

     Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin   BMI  \
0         6.0    148.0          72.0       35.0            NaN  33.6
1         1.0     85.0          66.0       29.0            NaN  26.6
2         8.0    183.0          64.0       29.0            NaN  23.3
3         1.0     89.0          66.0       23.0           94.0  28.1
4         0.0    137.0          40.0       35.0          168.0  43.1
..        ...      ...           ...        ...            ...   ...
763      10.0    101.0          76.0       48.0          180.0  32.9
764       2.0    122.0          70.0       27.0          180.0  36.8
765       5.0    121.0          72.0       23.0          112.0  26.2
766       1.0    126.0          60.0       23.0          112.0  30.1
767       1.0     93.0          70.0       31.0          112.0  30.4

     Diabetes_Pedigree   Age  Class
0                0.627  50.0    1.0
1                0.351  31.0    0.0
2                0.672  32.0    1.0
3                0.167  21.0    0.0
4                2.288  33.0    1.0
..                 ...   ...    ...
763              0.171  63.0    0.0
764              0.340  27.0    0.0
765              0.245  30.0    0.0
766              0.349  47.0    1.0
767              0.315  23.0    0.0

[768 rows x 9 columns]
     Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin   BMI  \
0         6.0    148.0          72.0       35.0           94.0  33.6
1         1.0     85.0          66.0       29.0           94.0  26.6
2         8.0    183.0          64.0       23.0           94.0  23.3
3         1.0     89.0          66.0       23.0           94.0  28.1
4         0.0    137.0          40.0       35.0          168.0  43.1
..        ...      ...           ...        ...            ...   ...
763      10.0    101.0          76.0       48.0          180.0  32.9
764       2.0    122.0          70.0       27.0          112.0  36.8
765       5.0    121.0          72.0       23.0          112.0  26.2
766       1.0    126.0          60.0       31.0            NaN  30.1
767       1.0     93.0          70.0       31.0            NaN  30.4

     Diabetes_Pedigree   Age  Class
0                0.627  50.0    1.0
1                0.351  31.0    0.0
2                0.672  32.0    1.0
3                0.167  21.0    0.0
4                2.288  33.0    1.0
..                 ...   ...    ...
763              0.171  63.0    0.0
764              0.340  27.0    0.0
765              0.245  30.0    0.0
766              0.349  47.0    1.0
767              0.315  23.0    0.0

[768 rows x 9 columns]

In [23]:
ar.ffill()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,29.0,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,180.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,23.0,112.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,112.0,30.4,0.315,23.0,0.0

In [24]:
ar.bfill()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,94.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,94.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,23.0,94.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,112.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,31.0,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [27]:
ar.fillna(value='ffill', axis=0)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,ffill,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,ffill,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,ffill,ffill,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,ffill,36.8,0.34,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,ffill,ffill,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,ffill,30.4,0.315,23.0,0.0

In [34]:
ar.ffill( axis=1)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,35.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,29.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,64.0,64.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,27.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,60.0,60.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,31.0,30.4,0.315,23.0,0.0

In [33]:
ar.bfill( axis=1)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,33.6,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,26.6,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,23.3,23.3,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,36.8,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,30.1,30.1,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,30.4,30.4,0.315,23.0,0.0

In [36]:
ar.fillna(0, limit= 2)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0.0

In [43]:
ar.ffill( limit=2)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,29.0,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,180.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,23.0,112.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,112.0,30.4,0.315,23.0,0.0

In [44]:
ar.fillna(5, inplace=True)
ar

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,5.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,5.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,5.0,5.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,5.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,5.0,5.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,5.0,30.4,0.315,23.0,0.0

In [45]:
ar

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6.0,148.0,72.0,35.0,5.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,5.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,5.0,5.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,5.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,5.0,5.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,5.0,30.4,0.315,23.0,0.0