## Pandas Method :

In [1]:
import pandas as pd

In [2]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  Yes      Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6   No       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     60
8    9   No      Suraj jadhav           D pharm    8.3     81
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     85
11  12   No  Vaishnavi Chavan             CSE-B    5.9     62
12  13  Yes      Rohini Agose           BA & MA    4.5     41
13  14  Yes      Sunil Jadhav              BAMS    3.3     42
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1     17
15  16   No       Namdev Zate         MPSC EXAM    8.9     95
16  17   No     Akash Sakhare        Civil Exam    2.5     30
17  18   No     Praful Jadhav           D pharm    1.9     24
18  19  Yes       Amol Ambore        Civil Engg    6.1     67
19  20  Yes  Vishal Jamvankar            AIML-C    7.4     69
20  21   No     Parth Dangare            AIML-B    2.7     30
21  22  Yes     Manisha Pande    12 th pass out    4.8     54
22  23   No    Lata Khachakad    12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [3]:
df.head()

   SR date          Nmes      Trades  Hours  Marks
0   1  Yes   Ajay Rathod         CSE    2.5     21
1   2  Yes   Vijay Agose          BA    5.1     47
2   3  Yes   Amol Jadhav  Mechanical    3.2     27
3   4  Yes  Surya Mekale  Electrical    8.5     75
4   5  Yes   Lakhan More         CSE    3.5     30

In [4]:
df.head(1)

   SR date         Nmes Trades  Hours  Marks
0   1  Yes  Ajay Rathod    CSE    2.5     21

In [5]:
df.head(12)

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  Yes      Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6   No       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     60
8    9   No      Suraj jadhav           D pharm    8.3     81
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     85
11  12   No  Vaishnavi Chavan             CSE-B    5.9     62

In [6]:
df.tail()

    SR date            Nmes          Trades  Hours  Marks
20  21   No   Parth Dangare          AIML-B    2.7     30
21  22  Yes   Manisha Pande  12 th pass out    4.8     54
22  23   No  Lata Khachakad  12 th pass out    3.8     35
23  24  Yes   Ganesh Jadhav   Lauary Driver    6.9     76
24  25   No  Dhanraj Jadhav   Bike Mechanic    7.8     86

In [7]:
df.tail(2)

    SR date            Nmes         Trades  Hours  Marks
23  24  Yes   Ganesh Jadhav  Lauary Driver    6.9     76
24  25   No  Dhanraj Jadhav  Bike Mechanic    7.8     86

In [8]:
df.tail(8)

    SR date              Nmes          Trades  Hours  Marks
17  18   No     Praful Jadhav         D pharm    1.9     24
18  19  Yes       Amol Ambore      Civil Engg    6.1     67
19  20  Yes  Vishal Jamvankar          AIML-C    7.4     69
20  21   No     Parth Dangare          AIML-B    2.7     30
21  22  Yes     Manisha Pande  12 th pass out    4.8     54
22  23   No    Lata Khachakad  12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav   Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav   Bike Mechanic    7.8     86

In [9]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", dtype = {'SR': 'float64'})
df

      SR date              Nmes            Trades  Hours  Marks
0    1.0  Yes       Ajay Rathod               CSE    2.5     21
1    2.0  Yes       Vijay Agose                BA    5.1     47
2    3.0  Yes       Amol Jadhav        Mechanical    3.2     27
3    4.0  Yes      Surya Mekale        Electrical    8.5     75
4    5.0  Yes       Lakhan More               CSE    3.5     30
5    6.0   No       Suyog Mohod               CSE    1.5     20
6    7.0   No    Santosh Rathod       Electrician    9.2     88
7    8.0   No    Saurabh Jadhav        Civil Exam    5.5     60
8    9.0   No      Suraj jadhav           D pharm    8.3     81
9   10.0   No     Kishor Jadhav    12 th pass out    2.7     25
10  11.0  Yes      Divya Jadhav  Electonics & CSE    7.7     85
11  12.0   No  Vaishnavi Chavan             CSE-B    5.9     62
12  13.0  Yes      Rohini Agose           BA & MA    4.5     41
13  14.0  Yes      Sunil Jadhav              BAMS    3.3     42
14  15.0  Yes  Jerrysing Rathod        Aramy Exam    1.1     17
15  16.0   No       Namdev Zate         MPSC EXAM    8.9     95
16  17.0   No     Akash Sakhare        Civil Exam    2.5     30
17  18.0   No     Praful Jadhav           D pharm    1.9     24
18  19.0  Yes       Amol Ambore        Civil Engg    6.1     67
19  20.0  Yes  Vishal Jamvankar            AIML-C    7.4     69
20  21.0   No     Parth Dangare            AIML-B    2.7     30
21  22.0  Yes     Manisha Pande    12 th pass out    4.8     54
22  23.0   No    Lata Khachakad    12 th pass out    3.8     35
23  24.0  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25.0   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [10]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", dtype = {'SR': 'float64', 'Marks':'float64'})
df

      SR date              Nmes            Trades  Hours  Marks
0    1.0  Yes       Ajay Rathod               CSE    2.5   21.0
1    2.0  Yes       Vijay Agose                BA    5.1   47.0
2    3.0  Yes       Amol Jadhav        Mechanical    3.2   27.0
3    4.0  Yes      Surya Mekale        Electrical    8.5   75.0
4    5.0  Yes       Lakhan More               CSE    3.5   30.0
5    6.0   No       Suyog Mohod               CSE    1.5   20.0
6    7.0   No    Santosh Rathod       Electrician    9.2   88.0
7    8.0   No    Saurabh Jadhav        Civil Exam    5.5   60.0
8    9.0   No      Suraj jadhav           D pharm    8.3   81.0
9   10.0   No     Kishor Jadhav    12 th pass out    2.7   25.0
10  11.0  Yes      Divya Jadhav  Electonics & CSE    7.7   85.0
11  12.0   No  Vaishnavi Chavan             CSE-B    5.9   62.0
12  13.0  Yes      Rohini Agose           BA & MA    4.5   41.0
13  14.0  Yes      Sunil Jadhav              BAMS    3.3   42.0
14  15.0  Yes  Jerrysing Rathod        Aramy Exam    1.1   17.0
15  16.0   No       Namdev Zate         MPSC EXAM    8.9   95.0
16  17.0   No     Akash Sakhare        Civil Exam    2.5   30.0
17  18.0   No     Praful Jadhav           D pharm    1.9   24.0
18  19.0  Yes       Amol Ambore        Civil Engg    6.1   67.0
19  20.0  Yes  Vishal Jamvankar            AIML-C    7.4   69.0
20  21.0   No     Parth Dangare            AIML-B    2.7   30.0
21  22.0  Yes     Manisha Pande    12 th pass out    4.8   54.0
22  23.0   No    Lata Khachakad    12 th pass out    3.8   35.0
23  24.0  Yes     Ganesh Jadhav     Lauary Driver    6.9   76.0
24  25.0   No    Dhanraj Jadhav     Bike Mechanic    7.8   86.0

In [11]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  Yes      Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6   No       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     60
8    9   No      Suraj jadhav           D pharm    8.3     81
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     85
11  12   No  Vaishnavi Chavan             CSE-B    5.9     62
12  13  Yes      Rohini Agose           BA & MA    4.5     41
13  14  Yes      Sunil Jadhav              BAMS    3.3     42
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1     17
15  16   No       Namdev Zate         MPSC EXAM    8.9     95
16  17   No     Akash Sakhare        Civil Exam    2.5     30
17  18   No     Praful Jadhav           D pharm    1.9     24
18  19  Yes       Amol Ambore        Civil Engg    6.1     67
19  20  Yes  Vishal Jamvankar            AIML-C    7.4     69
20  21   No     Parth Dangare            AIML-B    2.7     30
21  22  Yes     Manisha Pande    12 th pass out    4.8     54
22  23   No    Lata Khachakad    12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [12]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", true_values = ['Yes'])
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  Yes      Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6   No       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     60
8    9   No      Suraj jadhav           D pharm    8.3     81
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     85
11  12   No  Vaishnavi Chavan             CSE-B    5.9     62
12  13  Yes      Rohini Agose           BA & MA    4.5     41
13  14  Yes      Sunil Jadhav              BAMS    3.3     42
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1     17
15  16   No       Namdev Zate         MPSC EXAM    8.9     95
16  17   No     Akash Sakhare        Civil Exam    2.5     30
17  18   No     Praful Jadhav           D pharm    1.9     24
18  19  Yes       Amol Ambore        Civil Engg    6.1     67
19  20  Yes  Vishal Jamvankar            AIML-C    7.4     69
20  21   No     Parth Dangare            AIML-B    2.7     30
21  22  Yes     Manisha Pande    12 th pass out    4.8     54
22  23   No    Lata Khachakad    12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [13]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")
df

    SR date              Nmes            Trades  Hours  Marks
0    1  Yes       Ajay Rathod               CSE    2.5     21
1    2  Yes       Vijay Agose                BA    5.1     47
2    3  Yes       Amol Jadhav        Mechanical    3.2     27
3    4  Yes      Surya Mekale        Electrical    8.5     75
4    5  Yes       Lakhan More               CSE    3.5     30
5    6   No       Suyog Mohod               CSE    1.5     20
6    7   No    Santosh Rathod       Electrician    9.2     88
7    8   No    Saurabh Jadhav        Civil Exam    5.5     60
8    9   No      Suraj jadhav           D pharm    8.3     81
9   10   No     Kishor Jadhav    12 th pass out    2.7     25
10  11  Yes      Divya Jadhav  Electonics & CSE    7.7     85
11  12   No  Vaishnavi Chavan             CSE-B    5.9     62
12  13  Yes      Rohini Agose           BA & MA    4.5     41
13  14  Yes      Sunil Jadhav              BAMS    3.3     42
14  15  Yes  Jerrysing Rathod        Aramy Exam    1.1     17
15  16   No       Namdev Zate         MPSC EXAM    8.9     95
16  17   No     Akash Sakhare        Civil Exam    2.5     30
17  18   No     Praful Jadhav           D pharm    1.9     24
18  19  Yes       Amol Ambore        Civil Engg    6.1     67
19  20  Yes  Vishal Jamvankar            AIML-C    7.4     69
20  21   No     Parth Dangare            AIML-B    2.7     30
21  22  Yes     Manisha Pande    12 th pass out    4.8     54
22  23   No    Lata Khachakad    12 th pass out    3.8     35
23  24  Yes     Ganesh Jadhav     Lauary Driver    6.9     76
24  25   No    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [14]:
df =pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", true_values = ['Yes'], false_values = ['No'])
df

    SR   date              Nmes            Trades  Hours  Marks
0    1   True       Ajay Rathod               CSE    2.5     21
1    2   True       Vijay Agose                BA    5.1     47
2    3   True       Amol Jadhav        Mechanical    3.2     27
3    4   True      Surya Mekale        Electrical    8.5     75
4    5   True       Lakhan More               CSE    3.5     30
5    6  False       Suyog Mohod               CSE    1.5     20
6    7  False    Santosh Rathod       Electrician    9.2     88
7    8  False    Saurabh Jadhav        Civil Exam    5.5     60
8    9  False      Suraj jadhav           D pharm    8.3     81
9   10  False     Kishor Jadhav    12 th pass out    2.7     25
10  11   True      Divya Jadhav  Electonics & CSE    7.7     85
11  12  False  Vaishnavi Chavan             CSE-B    5.9     62
12  13   True      Rohini Agose           BA & MA    4.5     41
13  14   True      Sunil Jadhav              BAMS    3.3     42
14  15   True  Jerrysing Rathod        Aramy Exam    1.1     17
15  16  False       Namdev Zate         MPSC EXAM    8.9     95
16  17  False     Akash Sakhare        Civil Exam    2.5     30
17  18  False     Praful Jadhav           D pharm    1.9     24
18  19   True       Amol Ambore        Civil Engg    6.1     67
19  20   True  Vishal Jamvankar            AIML-C    7.4     69
20  21  False     Parth Dangare            AIML-B    2.7     30
21  22   True     Manisha Pande    12 th pass out    4.8     54
22  23  False    Lata Khachakad    12 th pass out    3.8     35
23  24   True     Ganesh Jadhav     Lauary Driver    6.9     76
24  25  False    Dhanraj Jadhav     Bike Mechanic    7.8     86