## Write CSV File in Pandas :

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv')
df

   Sr         Names      Branch
0   1   Ajay Rathod         CSE
1   2   Vijay Agose          BA
2   3   Amol Jadhav  Mechanical
3   4  Surya Mekale  Electrical
4   5   Lakhan More         CSE
5   6   Suyog Mohod         CSE

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.columns

Index(['Sr', 'Names', 'Branch'], dtype='str')

In [5]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', nrows =1)
df

   Sr        Names Branch
0   1  Ajay Rathod    CSE

In [6]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', nrows =4)
df

   Sr         Names      Branch
0   1   Ajay Rathod         CSE
1   2   Vijay Agose          BA
2   3   Amol Jadhav  Mechanical
3   4  Surya Mekale  Electrical

In [7]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', usecols=  [0])
df

   Sr
0   1
1   2
2   3
3   4
4   5
5   6

In [8]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', usecols=  [0,1])
df

   Sr         Names
0   1   Ajay Rathod
1   2   Vijay Agose
2   3   Amol Jadhav
3   4  Surya Mekale
4   5   Lakhan More
5   6   Suyog Mohod

In [9]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', usecols=  [1,2])
df

          Names      Branch
0   Ajay Rathod         CSE
1   Vijay Agose          BA
2   Amol Jadhav  Mechanical
3  Surya Mekale  Electrical
4   Lakhan More         CSE
5   Suyog Mohod         CSE

In [10]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', skiprows=1)
df

   1   Ajay Rathod         CSE
0  2   Vijay Agose          BA
1  3   Amol Jadhav  Mechanical
2  4  Surya Mekale  Electrical
3  5   Lakhan More         CSE
4  6   Suyog Mohod         CSE

In [11]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', skiprows =4)
df

   4 Surya Mekale Electrical
0  5  Lakhan More        CSE
1  6  Suyog Mohod        CSE

In [12]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', skiprows = [2])
df

   Sr         Names      Branch
0   1   Ajay Rathod         CSE
1   3   Amol Jadhav  Mechanical
2   4  Surya Mekale  Electrical
3   5   Lakhan More         CSE
4   6   Suyog Mohod         CSE

In [13]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', index_col = 'Sr')
df

           Names      Branch
Sr
1    Ajay Rathod         CSE
2    Vijay Agose          BA
3    Amol Jadhav  Mechanical
4   Surya Mekale  Electrical
5    Lakhan More         CSE
6    Suyog Mohod         CSE

In [14]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', index_col = 'Names')
df

              Sr      Branch
Names
Ajay Rathod    1         CSE
Vijay Agose    2          BA
Amol Jadhav    3  Mechanical
Surya Mekale   4  Electrical
Lakhan More    5         CSE
Suyog Mohod    6         CSE

In [15]:
df = pd.read_csv('C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv', index_col = 2)
df

            Sr         Names
Branch
CSE          1   Ajay Rathod
BA           2   Vijay Agose
Mechanical   3   Amol Jadhav
Electrical   4  Surya Mekale
CSE          5   Lakhan More
CSE          6   Suyog Mohod

# Write CSV Part-2 :

In [16]:
import pandas as pd

In [19]:
pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv")

     0                 1                 2      3       4
0   Sr             Names            Trades  Hours  Scores
1    1       Ajay Rathod               CSE    2.5      21
2    2       Vijay Agose                BA    5.1      47
3    3       Amol Jadhav        Mechanical    3.2      27
4    4      Surya Mekale        Electrical    8.5      75
5    5       Lakhan More               CSE    3.5      30
6    6       Suyog Mohod               CSE    1.5      20
7    7    Santosh Rathod       Electrician    9.2      88
8    8    Saurabh Jadhav        Civil Exam    5.5      60
9    9      Suraj jadhav           D pharm    8.3      81
10  10     Kishor Jadhav    12 th pass out    2.7      25
11  11      Divya Jadhav  Electonics & CSE    7.7      85
12  12  Vaishnavi Chavan             CSE-B    5.9      62
13  13      Rohini Agose           BA & MA    4.5      41
14  14      Sunil Jadhav              BAMS    3.3      42
15  15  Jerrysing Rathod        Aramy Exam    1.1      17
16  16       Namdev Zate         MPSC EXAM    8.9      95
17  17     Akash Sakhare        Civil Exam    2.5      30
18  18     Praful Jadhav           D pharm    1.9      24
19  19       Amol Ambore        Civil Engg    6.1      67
20  20  Vishal Jamvankar            AIML-C    7.4      69
21  21     Parth Dangare            AIML-B    2.7      30
22  22     Manisha Pande    12 th pass out    4.8      54
23  23    Lata Khachakad    12 th pass out    3.8      35
24  24     Ganesh Jadhav     Lauary Driver    6.9      76
25  25    Dhanraj Jadhav     Bike Mechanic    7.8      86

In [20]:
pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", header = 1)

    Sr             Names            Trades  Hours  Scores
0    1       Ajay Rathod               CSE    2.5      21
1    2       Vijay Agose                BA    5.1      47
2    3       Amol Jadhav        Mechanical    3.2      27
3    4      Surya Mekale        Electrical    8.5      75
4    5       Lakhan More               CSE    3.5      30
5    6       Suyog Mohod               CSE    1.5      20
6    7    Santosh Rathod       Electrician    9.2      88
7    8    Saurabh Jadhav        Civil Exam    5.5      60
8    9      Suraj jadhav           D pharm    8.3      81
9   10     Kishor Jadhav    12 th pass out    2.7      25
10  11      Divya Jadhav  Electonics & CSE    7.7      85
11  12  Vaishnavi Chavan             CSE-B    5.9      62
12  13      Rohini Agose           BA & MA    4.5      41
13  14      Sunil Jadhav              BAMS    3.3      42
14  15  Jerrysing Rathod        Aramy Exam    1.1      17
15  16       Namdev Zate         MPSC EXAM    8.9      95
16  17     Akash Sakhare        Civil Exam    2.5      30
17  18     Praful Jadhav           D pharm    1.9      24
18  19       Amol Ambore        Civil Engg    6.1      67
19  20  Vishal Jamvankar            AIML-C    7.4      69
20  21     Parth Dangare            AIML-B    2.7      30
21  22     Manisha Pande    12 th pass out    4.8      54
22  23    Lata Khachakad    12 th pass out    3.8      35
23  24     Ganesh Jadhav     Lauary Driver    6.9      76
24  25    Dhanraj Jadhav     Bike Mechanic    7.8      86

In [21]:
pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", header =None )

     0                 1                 2    3   4
0    1       Ajay Rathod               CSE  2.5  21
1    2       Vijay Agose                BA  5.1  47
2    3       Amol Jadhav        Mechanical  3.2  27
3    4      Surya Mekale        Electrical  8.5  75
4    5       Lakhan More               CSE  3.5  30
5    6       Suyog Mohod               CSE  1.5  20
6    7    Santosh Rathod       Electrician  9.2  88
7    8    Saurabh Jadhav        Civil Exam  5.5  60
8    9      Suraj jadhav           D pharm  8.3  81
9   10     Kishor Jadhav    12 th pass out  2.7  25
10  11      Divya Jadhav  Electonics & CSE  7.7  85
11  12  Vaishnavi Chavan             CSE-B  5.9  62
12  13      Rohini Agose           BA & MA  4.5  41
13  14      Sunil Jadhav              BAMS  3.3  42
14  15  Jerrysing Rathod        Aramy Exam  1.1  17
15  16       Namdev Zate         MPSC EXAM  8.9  95
16  17     Akash Sakhare        Civil Exam  2.5  30
17  18     Praful Jadhav           D pharm  1.9  24
18  19       Amol Ambore        Civil Engg  6.1  67
19  20  Vishal Jamvankar            AIML-C  7.4  69
20  21     Parth Dangare            AIML-B  2.7  30
21  22     Manisha Pande    12 th pass out  4.8  54
22  23    Lata Khachakad    12 th pass out  3.8  35
23  24     Ganesh Jadhav     Lauary Driver  6.9  76
24  25    Dhanraj Jadhav     Bike Mechanic  7.8  86

Parameter Prefix

In [33]:
df1 = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", header =None)
df1.add_prefix('Columns')

    Columns0          Columns1          Columns2  Columns3  Columns4
0          1       Ajay Rathod               CSE       2.5        21
1          2       Vijay Agose                BA       5.1        47
2          3       Amol Jadhav        Mechanical       3.2        27
3          4      Surya Mekale        Electrical       8.5        75
4          5       Lakhan More               CSE       3.5        30
5          6       Suyog Mohod               CSE       1.5        20
6          7    Santosh Rathod       Electrician       9.2        88
7          8    Saurabh Jadhav        Civil Exam       5.5        60
8          9      Suraj jadhav           D pharm       8.3        81
9         10     Kishor Jadhav    12 th pass out       2.7        25
10        11      Divya Jadhav  Electonics & CSE       7.7        85
11        12  Vaishnavi Chavan             CSE-B       5.9        62
12        13      Rohini Agose           BA & MA       4.5        41
13        14      Sunil Jadhav              BAMS       3.3        42
14        15  Jerrysing Rathod        Aramy Exam       1.1        17
15        16       Namdev Zate         MPSC EXAM       8.9        95
16        17     Akash Sakhare        Civil Exam       2.5        30
17        18     Praful Jadhav           D pharm       1.9        24
18        19       Amol Ambore        Civil Engg       6.1        67
19        20  Vishal Jamvankar            AIML-C       7.4        69
20        21     Parth Dangare            AIML-B       2.7        30
21        22     Manisha Pande    12 th pass out       4.8        54
22        23    Lata Khachakad    12 th pass out       3.8        35
23        24     Ganesh Jadhav     Lauary Driver       6.9        76
24        25    Dhanraj Jadhav     Bike Mechanic       7.8        86

In [34]:
df1 = pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", header =None)
df1.add_prefix('Data')

    Data0             Data1             Data2  Data3  Data4
0       1       Ajay Rathod               CSE    2.5     21
1       2       Vijay Agose                BA    5.1     47
2       3       Amol Jadhav        Mechanical    3.2     27
3       4      Surya Mekale        Electrical    8.5     75
4       5       Lakhan More               CSE    3.5     30
5       6       Suyog Mohod               CSE    1.5     20
6       7    Santosh Rathod       Electrician    9.2     88
7       8    Saurabh Jadhav        Civil Exam    5.5     60
8       9      Suraj jadhav           D pharm    8.3     81
9      10     Kishor Jadhav    12 th pass out    2.7     25
10     11      Divya Jadhav  Electonics & CSE    7.7     85
11     12  Vaishnavi Chavan             CSE-B    5.9     62
12     13      Rohini Agose           BA & MA    4.5     41
13     14      Sunil Jadhav              BAMS    3.3     42
14     15  Jerrysing Rathod        Aramy Exam    1.1     17
15     16       Namdev Zate         MPSC EXAM    8.9     95
16     17     Akash Sakhare        Civil Exam    2.5     30
17     18     Praful Jadhav           D pharm    1.9     24
18     19       Amol Ambore        Civil Engg    6.1     67
19     20  Vishal Jamvankar            AIML-C    7.4     69
20     21     Parth Dangare            AIML-B    2.7     30
21     22     Manisha Pande    12 th pass out    4.8     54
22     23    Lata Khachakad    12 th pass out    3.8     35
23     24     Ganesh Jadhav     Lauary Driver    6.9     76
24     25    Dhanraj Jadhav     Bike Mechanic    7.8     86

In [40]:
pd.read_csv("C:\\Users\\ajayr\\OneDrive\\Documents\\Friends Name.csv", names = ['SR', 'Names', 'Trades', 'Hours', 'Marks'])

    SR             Names            Trades  Hours  Marks
0    1       Ajay Rathod               CSE    2.5     21
1    2       Vijay Agose                BA    5.1     47
2    3       Amol Jadhav        Mechanical    3.2     27
3    4      Surya Mekale        Electrical    8.5     75
4    5       Lakhan More               CSE    3.5     30
5    6       Suyog Mohod               CSE    1.5     20
6    7    Santosh Rathod       Electrician    9.2     88
7    8    Saurabh Jadhav        Civil Exam    5.5     60
8    9      Suraj jadhav           D pharm    8.3     81
9   10     Kishor Jadhav    12 th pass out    2.7     25
10  11      Divya Jadhav  Electonics & CSE    7.7     85
11  12  Vaishnavi Chavan             CSE-B    5.9     62
12  13      Rohini Agose           BA & MA    4.5     41
13  14      Sunil Jadhav              BAMS    3.3     42
14  15  Jerrysing Rathod        Aramy Exam    1.1     17
15  16       Namdev Zate         MPSC EXAM    8.9     95
16  17     Akash Sakhare        Civil Exam    2.5     30
17  18     Praful Jadhav           D pharm    1.9     24
18  19       Amol Ambore        Civil Engg    6.1     67
19  20  Vishal Jamvankar            AIML-C    7.4     69
20  21     Parth Dangare            AIML-B    2.7     30
21  22     Manisha Pande    12 th pass out    4.8     54
22  23    Lata Khachakad    12 th pass out    3.8     35
23  24     Ganesh Jadhav     Lauary Driver    6.9     76
24  25    Dhanraj Jadhav     Bike Mechanic    7.8     86